// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations (this file, used by `prisma migrate deploy`) need a direct
    // connection — Neon's pooled endpoint doesn't reliably support the
    // session-level advisory locks Prisma Migrate uses. The app itself
    // (src/lib/db.ts) still connects via the pooled DATABASE_URL at
    // runtime, which is what you want for normal queries.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],

    // Only needed to *author* a migration locally: `prisma migrate diff`
    // replays the existing migrations into a scratch database to work out what
    // changed. Unset in production, where migrations are only ever applied
    // (`prisma migrate deploy`) and nothing is diffed.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
