-- Mairo Assist: complete database setup for a NEW Supabase project.
-- Generated by scripts/build-setup-sql.sh from supabase/migrations/. Do not edit by hand.
-- Paste this whole file into Supabase → SQL Editor and click Run, once.

-- ============================================================
-- 20260924000100_core_tenancy.sql
-- ============================================================
-- Mairo Assist — core tenancy, identity, roles, audit, jobs and rate limits.
--
-- Conventions used by every migration in this folder:
--   * Internal IDs are uuid (gen_random_uuid()).
--   * Every tenant-owned row carries business_id, with a foreign key to
--     businesses and ON DELETE CASCADE so deleting a business removes its data.
--   * External Shopify IDs are stored as the GraphQL global ID text
--     ("gid://shopify/Product/123") in a column named shopify_gid, unique per
--     business.
--   * Enumerations are text + CHECK constraints (easier to evolve than enums).
--   * RLS is enabled on every table. Tables that hold secrets or system state
--     have RLS on and NO policies, and are revoked from anon/authenticated,
--     so only the server's service role can touch them.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Shared trigger: keep updated_at current.
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- users: the application profile for an auth.users row.
-- ---------------------------------------------------------------------------
create table public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  full_name text check (char_length(full_name) <= 120),
  avatar_url text check (char_length(avatar_url) <= 2048),
  dashboard_view text not null default 'simple' check (dashboard_view in ('simple', 'advanced')),
  last_business_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger users_set_updated_at before update on public.users
  for each row execute function public.set_updated_at();

-- Create / sync the profile whenever Supabase Auth creates or changes a user.
create or replace function public.handle_auth_user_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.users (id, email, full_name)
    values (
      new.id,
      lower(new.email),
      nullif(left(coalesce(new.raw_user_meta_data ->> 'full_name', ''), 120), '')
    )
    on conflict (id) do nothing;
  elsif tg_op = 'UPDATE' and new.email is distinct from old.email then
    update public.users set email = lower(new.email) where id = new.id;
  end if;
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_auth_user_change();
create trigger on_auth_user_email_changed after update of email on auth.users
  for each row execute function public.handle_auth_user_change();

-- ---------------------------------------------------------------------------
-- Platform administrators (Mairo Assist staff). Service role only.
-- ---------------------------------------------------------------------------
create table public.platform_admins (
  user_id uuid primary key references public.users (id) on delete cascade,
  role text not null check (role in ('superadmin', 'operations', 'support', 'finance')),
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- businesses: the tenant.
-- ---------------------------------------------------------------------------
create table public.businesses (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'),
  website_url text check (char_length(website_url) <= 2048),
  industry text check (char_length(industry) <= 80),
  description text check (char_length(description) <= 2000),
  sells text[] not null default '{}'
    check (sells <@ array['physical', 'digital', 'services', 'other']::text[]),
  ai_goals text[] not null default '{}'
    check (ai_goals <@ array['customer_support', 'sales_assistance', 'product_recommendations',
                             'order_tracking', 'returns_exchanges', 'lead_collection']::text[]),
  status text not null default 'active' check (status in ('active', 'suspended', 'deletion_requested')),
  deletion_requested_at timestamptz,
  created_by uuid references public.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger businesses_set_updated_at before update on public.businesses
  for each row execute function public.set_updated_at();

alter table public.users
  add constraint users_last_business_fk foreign key (last_business_id)
  references public.businesses (id) on delete set null;

-- ---------------------------------------------------------------------------
-- business_members: who belongs to which business, with which role.
-- `permissions` holds optional extra grants for admins (validated in the app
-- against a fixed grantable list; never grants billing management).
-- ---------------------------------------------------------------------------
create table public.business_members (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'support_agent')),
  permissions jsonb not null default '{}'::jsonb check (jsonb_typeof(permissions) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create index business_members_user_idx on public.business_members (user_id);

create trigger business_members_set_updated_at before update on public.business_members
  for each row execute function public.set_updated_at();

-- A business must always keep at least one owner.
create or replace function public.ensure_business_keeps_owner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.role = 'owner' and (tg_op = 'DELETE' or new.role <> 'owner') then
    -- Cascading delete of the whole business is fine.
    if not exists (select 1 from public.businesses b where b.id = old.business_id) then
      return coalesce(new, old);
    end if;
    if not exists (
      select 1 from public.business_members m
      where m.business_id = old.business_id and m.role = 'owner' and m.id <> old.id
    ) then
      raise exception 'A business must keep at least one owner' using errcode = 'P0001';
    end if;
  end if;
  return coalesce(new, old);
end;
$$;

create trigger business_members_keep_owner
  before update of role or delete on public.business_members
  for each row execute function public.ensure_business_keeps_owner();

-- ---------------------------------------------------------------------------
-- RLS helper functions. SECURITY DEFINER so policies on business_members do
-- not recurse. They only ever answer about the *calling* user (auth.uid()).
-- ---------------------------------------------------------------------------
create or replace function public.is_business_member(p_business_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.business_members m
    join public.businesses b on b.id = m.business_id
    where m.business_id = p_business_id
      and m.user_id = auth.uid()
      and b.status <> 'suspended'
  );
$$;

create or replace function public.has_business_role(p_business_id uuid, p_roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.business_members m
    join public.businesses b on b.id = m.business_id
    where m.business_id = p_business_id
      and m.user_id = auth.uid()
      and m.role = any (p_roles)
      and b.status <> 'suspended'
  );
$$;

create or replace function public.shares_business_with(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.business_members mine
    join public.business_members theirs on theirs.business_id = mine.business_id
    where mine.user_id = auth.uid() and theirs.user_id = p_user_id
  );
$$;

-- ---------------------------------------------------------------------------
-- business_settings: one row per business; onboarding progress lives here.
-- ---------------------------------------------------------------------------
create table public.business_settings (
  business_id uuid primary key references public.businesses (id) on delete cascade,
  onboarding_step smallint not null default 1 check (onboarding_step between 1 and 9),
  onboarding_completed_at timestamptz,
  shopify_step_skipped boolean not null default false,
  timezone text not null default 'UTC' check (char_length(timezone) <= 64),
  support_email text check (char_length(support_email) <= 320),
  escalation_email text check (char_length(escalation_email) <= 320),
  -- How long conversation content is kept before the retention job removes it.
  conversation_retention_days integer not null default 365
    check (conversation_retention_days between 30 and 3650),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger business_settings_set_updated_at before update on public.business_settings
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- business_invitations: owner-issued invites. Only a SHA-256 hash of the
-- token is stored; the plain token is shown once to the inviter.
-- ---------------------------------------------------------------------------
create table public.business_invitations (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  email text not null check (email = lower(email) and char_length(email) <= 320),
  role text not null check (role in ('admin', 'support_agent')),
  token_hash text not null unique,
  invited_by uuid references public.users (id) on delete set null,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references public.users (id) on delete set null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index business_invitations_one_pending_idx
  on public.business_invitations (business_id, email)
  where accepted_at is null and revoked_at is null;

-- ---------------------------------------------------------------------------
-- Audit logs: append-only record of important administrative actions.
-- ---------------------------------------------------------------------------
create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references public.businesses (id) on delete cascade,
  actor_type text not null check (actor_type in ('user', 'platform_admin', 'system', 'ai')),
  actor_user_id uuid references public.users (id) on delete set null,
  action text not null check (char_length(action) <= 120),
  target_type text check (char_length(target_type) <= 60),
  target_id text check (char_length(target_id) <= 200),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index audit_logs_business_created_idx on public.audit_logs (business_id, created_at desc);

create or replace function public.prevent_audit_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Rows vanish only through the cascade when their business is deleted.
  if tg_op = 'DELETE' and not exists (select 1 from public.businesses b where b.id = old.business_id) then
    return old;
  end if;
  raise exception 'audit_logs is append-only' using errcode = 'P0001';
end;
$$;

create trigger audit_logs_append_only before update or delete on public.audit_logs
  for each row execute function public.prevent_audit_mutation();

-- ---------------------------------------------------------------------------
-- Activity logs: the merchant-facing activity feed. Only written by the
-- server when an event actually happened.
-- ---------------------------------------------------------------------------
create table public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  type text not null check (char_length(type) <= 60),
  summary text not null check (char_length(summary) <= 500),
  conversation_id uuid,
  customer_id uuid,
  order_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index activity_logs_business_created_idx on public.activity_logs (business_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Background jobs: a Postgres-backed queue (webhook processing, syncs,
-- retention). Claimed with FOR UPDATE SKIP LOCKED, retried with backoff.
-- ---------------------------------------------------------------------------
create table public.background_jobs (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references public.businesses (id) on delete cascade,
  type text not null check (char_length(type) <= 80),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued', 'running', 'succeeded', 'failed', 'dead')),
  idempotency_key text unique,
  run_at timestamptz not null default now(),
  attempts integer not null default 0,
  max_attempts integer not null default 8 check (max_attempts between 1 and 50),
  locked_at timestamptz,
  locked_by text,
  last_error text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index background_jobs_ready_idx on public.background_jobs (run_at) where status in ('queued', 'running');
create index background_jobs_failed_idx on public.background_jobs (updated_at desc) where status in ('failed', 'dead');

create trigger background_jobs_set_updated_at before update on public.background_jobs
  for each row execute function public.set_updated_at();

-- Claim up to p_limit runnable jobs. A job stuck in 'running' for more than
-- p_stale_seconds (a crashed worker) becomes claimable again.
create or replace function public.claim_background_jobs(p_worker text, p_limit integer default 10, p_stale_seconds integer default 600)
returns setof public.background_jobs
language sql
security definer
set search_path = ''
as $$
  update public.background_jobs j
  set status = 'running', locked_at = now(), locked_by = p_worker, attempts = j.attempts + 1
  where j.id in (
    select id from public.background_jobs
    where run_at <= now()
      and (status = 'queued'
           or (status = 'running' and locked_at < now() - make_interval(secs => p_stale_seconds)))
    order by run_at
    for update skip locked
    limit greatest(1, least(p_limit, 100))
  )
  returning j.*;
$$;

-- Record a job failure: retry with exponential backoff, or mark dead.
create or replace function public.fail_background_job(p_job_id uuid, p_error text)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.background_jobs
  set status = case when attempts >= max_attempts then 'dead' else 'queued' end,
      run_at = now() + make_interval(secs => least(3600, (30 * power(2, least(attempts, 10)))::integer)),
      locked_at = null,
      locked_by = null,
      last_error = left(p_error, 2000)
  where id = p_job_id;
$$;

-- ---------------------------------------------------------------------------
-- Rate limiting: fixed-window counters keyed by an opaque string
-- (e.g. "widget:ip:<hash>"). Returns true when the hit is allowed.
-- ---------------------------------------------------------------------------
create table public.rate_limits (
  key text not null,
  window_start timestamptz not null,
  hits integer not null default 0,
  primary key (key, window_start)
);

create or replace function public.rate_limit_hit(p_key text, p_limit integer, p_window_seconds integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_window timestamptz := to_timestamp(floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds);
  v_hits integer;
begin
  insert into public.rate_limits as r (key, window_start, hits)
  values (p_key, v_window, 1)
  on conflict (key, window_start) do update set hits = r.hits + 1
  returning hits into v_hits;
  return v_hits <= p_limit;
end;
$$;

-- ---------------------------------------------------------------------------
-- RPC: create a business and make the caller its owner, atomically.
-- ---------------------------------------------------------------------------
create or replace function public.create_business(
  p_name text,
  p_website_url text default null,
  p_industry text default null,
  p_description text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_base text;
  v_slug text;
  v_business uuid;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;
  if (select count(*) from public.business_members where user_id = v_user and role = 'owner') >= 10 then
    raise exception 'Business limit reached' using errcode = 'P0001';
  end if;

  v_base := trim(both '-' from regexp_replace(lower(coalesce(p_name, '')), '[^a-z0-9]+', '-', 'g'));
  v_base := left(coalesce(nullif(v_base, ''), 'business'), 48);
  v_base := trim(both '-' from v_base);
  v_slug := v_base;
  while exists (select 1 from public.businesses where slug = v_slug) loop
    v_slug := v_base || '-' || substr(md5(gen_random_uuid()::text), 1, 6);
  end loop;

  insert into public.businesses (name, slug, website_url, industry, description, created_by)
  values (trim(p_name), v_slug, nullif(trim(p_website_url), ''), nullif(trim(p_industry), ''),
          nullif(trim(p_description), ''), v_user)
  returning id into v_business;

  insert into public.business_members (business_id, user_id, role) values (v_business, v_user, 'owner');
  insert into public.business_settings (business_id, onboarding_step) values (v_business, 2);
  update public.users set last_business_id = v_business where id = v_user;

  insert into public.audit_logs (business_id, actor_type, actor_user_id, action, target_type, target_id)
  values (v_business, 'user', v_user, 'business.created', 'business', v_business::text);

  return v_business;
end;
$$;

-- ---------------------------------------------------------------------------
-- RPC: accept an invitation addressed to the caller's verified email.
-- ---------------------------------------------------------------------------
create or replace function public.accept_business_invitation(p_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_inv public.business_invitations;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  select * into v_inv
  from public.business_invitations
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  for update;

  if v_inv.id is null or v_inv.revoked_at is not null or v_inv.accepted_at is not null
     or v_inv.expires_at < now() then
    raise exception 'This invitation is invalid or has expired' using errcode = 'P0001';
  end if;
  if v_inv.email <> v_email then
    raise exception 'This invitation was sent to a different email address' using errcode = 'P0001';
  end if;

  insert into public.business_members (business_id, user_id, role)
  values (v_inv.business_id, v_user, v_inv.role)
  on conflict (business_id, user_id) do nothing;

  update public.business_invitations
  set accepted_at = now(), accepted_by = v_user
  where id = v_inv.id;

  update public.users set last_business_id = v_inv.business_id where id = v_user;

  insert into public.audit_logs (business_id, actor_type, actor_user_id, action, target_type, target_id, metadata)
  values (v_inv.business_id, 'user', v_user, 'team.invitation_accepted', 'invitation', v_inv.id::text,
          jsonb_build_object('role', v_inv.role));

  return v_inv.business_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- RPCs: list / revoke the caller's own Auth sessions (device management).
-- ---------------------------------------------------------------------------
create or replace function public.list_my_sessions()
returns table (id uuid, created_at timestamptz, updated_at timestamptz, user_agent text, ip text)
language sql
stable
security definer
set search_path = ''
as $$
  select s.id, s.created_at, coalesce(s.refreshed_at::timestamptz, s.updated_at), s.user_agent, host(s.ip)
  from auth.sessions s
  where s.user_id = auth.uid()
  order by coalesce(s.refreshed_at::timestamptz, s.updated_at) desc nulls last
  limit 50;
$$;

create or replace function public.revoke_my_session(p_session_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  delete from auth.sessions where id = p_session_id and user_id = auth.uid();
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
alter table public.users enable row level security;
alter table public.platform_admins enable row level security;
alter table public.businesses enable row level security;
alter table public.business_members enable row level security;
alter table public.business_settings enable row level security;
alter table public.business_invitations enable row level security;
alter table public.audit_logs enable row level security;
alter table public.activity_logs enable row level security;
alter table public.background_jobs enable row level security;
alter table public.rate_limits enable row level security;

-- users
create policy users_select_self_or_teammate on public.users for select to authenticated
  using (id = (select auth.uid()) or public.shares_business_with(id));
create policy users_update_self on public.users for update to authenticated
  using (id = (select auth.uid())) with check (id = (select auth.uid()));

-- businesses
create policy businesses_select_member on public.businesses for select to authenticated
  using (public.is_business_member(id));
create policy businesses_update_manager on public.businesses for update to authenticated
  using (public.has_business_role(id, array['owner', 'admin']))
  with check (public.has_business_role(id, array['owner', 'admin']));

-- business_members
create policy members_select_same_business on public.business_members for select to authenticated
  using (public.is_business_member(business_id));
create policy members_update_owner on public.business_members for update to authenticated
  using (public.has_business_role(business_id, array['owner']))
  with check (public.has_business_role(business_id, array['owner']));
create policy members_delete_owner_or_self on public.business_members for delete to authenticated
  using (public.has_business_role(business_id, array['owner']) or user_id = (select auth.uid()));

-- business_settings
create policy settings_select_member on public.business_settings for select to authenticated
  using (public.is_business_member(business_id));
create policy settings_update_manager on public.business_settings for update to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']))
  with check (public.has_business_role(business_id, array['owner', 'admin']));

-- business_invitations (owners manage the team)
create policy invitations_select_owner on public.business_invitations for select to authenticated
  using (public.has_business_role(business_id, array['owner']));
create policy invitations_insert_owner on public.business_invitations for insert to authenticated
  with check (public.has_business_role(business_id, array['owner']) and invited_by = (select auth.uid()));
create policy invitations_update_owner on public.business_invitations for update to authenticated
  using (public.has_business_role(business_id, array['owner']))
  with check (public.has_business_role(business_id, array['owner']));

-- audit / activity
create policy audit_select_manager on public.audit_logs for select to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));
create policy activity_select_member on public.activity_logs for select to authenticated
  using (public.is_business_member(business_id));

-- platform_admins, background_jobs, rate_limits: no policies (service role only).

-- ---------------------------------------------------------------------------
-- Privileges. Supabase grants broad table privileges to anon/authenticated by
-- default; RLS is the real gate, but narrow the surface anyway.
-- ---------------------------------------------------------------------------
revoke all on public.users, public.platform_admins, public.businesses, public.business_members,
  public.business_settings, public.business_invitations, public.audit_logs, public.activity_logs,
  public.background_jobs, public.rate_limits
  from anon;
revoke all on public.platform_admins, public.background_jobs, public.rate_limits from authenticated;
revoke insert, update, delete on public.audit_logs, public.activity_logs from authenticated;
revoke insert, delete on public.users, public.businesses, public.business_settings from authenticated;
revoke insert on public.business_members from authenticated;

-- Column-level update grants: users may not change identity or system columns.
revoke update on public.users from authenticated;
grant update (full_name, avatar_url, dashboard_view, last_business_id) on public.users to authenticated;
revoke update on public.businesses from authenticated;
grant update (name, website_url, industry, description, sells, ai_goals) on public.businesses to authenticated;
revoke update on public.business_members from authenticated;
grant update (role, permissions) on public.business_members to authenticated;
revoke update on public.business_settings from authenticated;
grant update (onboarding_step, onboarding_completed_at, shopify_step_skipped, timezone, support_email,
              escalation_email, conversation_retention_days)
  on public.business_settings to authenticated;
revoke update on public.business_invitations from authenticated;
grant update (revoked_at) on public.business_invitations to authenticated;

-- Functions: only what the app needs, only to the roles that need it.
revoke execute on function public.claim_background_jobs(text, integer, integer) from public, anon, authenticated;
revoke execute on function public.fail_background_job(uuid, text) from public, anon, authenticated;
revoke execute on function public.rate_limit_hit(text, integer, integer) from public, anon, authenticated;
revoke execute on function public.create_business(text, text, text, text) from public, anon;
revoke execute on function public.accept_business_invitation(text) from public, anon;
revoke execute on function public.list_my_sessions() from public, anon;
revoke execute on function public.revoke_my_session(uuid) from public, anon;
revoke execute on function public.handle_auth_user_change() from public, anon, authenticated;
grant execute on function public.create_business(text, text, text, text) to authenticated;
grant execute on function public.accept_business_invitation(text) to authenticated;
grant execute on function public.list_my_sessions() to authenticated;
grant execute on function public.revoke_my_session(uuid) to authenticated;
grant execute on function public.claim_background_jobs(text, integer, integer) to service_role;
grant execute on function public.fail_background_job(uuid, text) to service_role;
grant execute on function public.rate_limit_hit(text, integer, integer) to service_role;

-- ============================================================
-- 20260924000200_ai_employee_knowledge.sql
-- ============================================================
-- Mairo Assist — AI employee configuration, versions, and knowledge base.

-- ---------------------------------------------------------------------------
-- ai_employees: one AI employee per business (for now).
--   draft_config     — what the owner is editing (validated by the app).
--   published_version_id — what customers actually talk to.
-- An employee can only be 'active' once a version is published AND it has
-- been tested in preview: an untested assistant is never switched on.
-- ---------------------------------------------------------------------------
create table public.ai_employees (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null unique references public.businesses (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 40),
  avatar_url text check (char_length(avatar_url) <= 2048),
  status text not null default 'draft' check (status in ('draft', 'active', 'paused')),
  draft_config jsonb not null default '{}'::jsonb check (jsonb_typeof(draft_config) = 'object'),
  published_version_id uuid,
  tested_at timestamptz,
  activated_at timestamptz,
  paused_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_employees_active_requires_tested_publish
    check (status <> 'active' or (published_version_id is not null and tested_at is not null))
);

create trigger ai_employees_set_updated_at before update on public.ai_employees
  for each row execute function public.set_updated_at();

create table public.ai_employee_versions (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  ai_employee_id uuid not null references public.ai_employees (id) on delete cascade,
  version integer not null check (version > 0),
  name text not null,
  config jsonb not null check (jsonb_typeof(config) = 'object'),
  note text check (char_length(note) <= 280),
  created_by uuid references public.users (id) on delete set null,
  published_at timestamptz not null default now(),
  unique (ai_employee_id, version)
);

create index ai_employee_versions_business_idx on public.ai_employee_versions (business_id, published_at desc);

alter table public.ai_employees
  add constraint ai_employees_published_version_fk foreign key (published_version_id)
  references public.ai_employee_versions (id) on delete set null;

-- The published version must belong to the same employee.
create or replace function public.check_published_version_owner()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.published_version_id is not null and not exists (
    select 1 from public.ai_employee_versions v
    where v.id = new.published_version_id and v.ai_employee_id = new.id
  ) then
    raise exception 'Published version does not belong to this AI employee' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger ai_employees_check_version before insert or update of published_version_id on public.ai_employees
  for each row execute function public.check_published_version_owner();

-- ---------------------------------------------------------------------------
-- Knowledge base. Documents are tenant-isolated; chunks are the indexed text
-- the AI retrieves from (full-text search now; vector embeddings are added
-- with the AI conversation phase).
-- ---------------------------------------------------------------------------
create table public.knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  category text not null check (category in (
    'shipping_policy', 'refund_policy', 'return_policy', 'product_info', 'sizing_guide', 'faq',
    'company_background', 'business_hours', 'contact_info', 'support_instructions', 'other'
  )),
  source_type text not null check (source_type in ('manual', 'upload', 'shopify_policy')),
  storage_path text check (char_length(storage_path) <= 1024),
  mime_type text check (char_length(mime_type) <= 120),
  size_bytes integer check (size_bytes between 0 and 10485760),
  content text check (char_length(content) <= 200000),
  status text not null default 'ready' check (status in ('pending', 'processing', 'ready', 'failed')),
  error text,
  created_by uuid references public.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index knowledge_documents_business_idx on public.knowledge_documents (business_id, category);

create trigger knowledge_documents_set_updated_at before update on public.knowledge_documents
  for each row execute function public.set_updated_at();

create table public.knowledge_chunks (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  document_id uuid not null references public.knowledge_documents (id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null,
  token_count integer,
  tsv tsvector generated always as (to_tsvector('english', content)) stored,
  created_at timestamptz not null default now(),
  unique (document_id, chunk_index)
);

create index knowledge_chunks_business_idx on public.knowledge_chunks (business_id);
create index knowledge_chunks_tsv_idx on public.knowledge_chunks using gin (tsv);

-- Chunks must belong to the same business as their document.
create or replace function public.check_same_business_document()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.knowledge_documents d where d.id = new.document_id and d.business_id = new.business_id
  ) then
    raise exception 'Chunk business does not match document business' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger knowledge_chunks_same_business before insert or update on public.knowledge_chunks
  for each row execute function public.check_same_business_document();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.ai_employees enable row level security;
alter table public.ai_employee_versions enable row level security;
alter table public.knowledge_documents enable row level security;
alter table public.knowledge_chunks enable row level security;

create policy ai_employees_select_member on public.ai_employees for select to authenticated
  using (public.is_business_member(business_id));
create policy ai_employees_insert_manager on public.ai_employees for insert to authenticated
  with check (public.has_business_role(business_id, array['owner', 'admin']));
create policy ai_employees_update_manager on public.ai_employees for update to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']))
  with check (public.has_business_role(business_id, array['owner', 'admin']));

create policy ai_versions_select_manager on public.ai_employee_versions for select to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));

create policy knowledge_documents_select_member on public.knowledge_documents for select to authenticated
  using (public.is_business_member(business_id));
create policy knowledge_documents_insert_manager on public.knowledge_documents for insert to authenticated
  with check (public.has_business_role(business_id, array['owner', 'admin'])
              and created_by = (select auth.uid()) and source_type = 'manual');
create policy knowledge_documents_update_manager on public.knowledge_documents for update to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']))
  with check (public.has_business_role(business_id, array['owner', 'admin']));
create policy knowledge_documents_delete_manager on public.knowledge_documents for delete to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));

create policy knowledge_chunks_select_member on public.knowledge_chunks for select to authenticated
  using (public.is_business_member(business_id));

revoke all on public.ai_employees, public.ai_employee_versions, public.knowledge_documents,
  public.knowledge_chunks from anon;
revoke delete on public.ai_employees from authenticated;
revoke insert, update, delete on public.ai_employee_versions, public.knowledge_chunks from authenticated;

-- Status, testing and publishing move only through the server (which checks
-- the tested/published invariants and writes the audit trail).
revoke update on public.ai_employees from authenticated;
grant update (name, avatar_url, draft_config) on public.ai_employees to authenticated;
revoke update on public.knowledge_documents from authenticated;
grant update (title, category, content) on public.knowledge_documents to authenticated;
revoke insert on public.ai_employees from authenticated;
grant insert (business_id, name, avatar_url, draft_config) on public.ai_employees to authenticated;
revoke insert on public.knowledge_documents from authenticated;
grant insert (business_id, title, category, source_type, content, created_by) on public.knowledge_documents to authenticated;

-- ============================================================
-- 20260924000300_commerce.sql
-- ============================================================
-- Mairo Assist — Shopify connection, catalog, customers and orders.
--
-- All commerce rows are written by the server (service role) from Shopify
-- data. Dashboard users only read them through RLS. Access tokens live in a
-- separate table no browser-facing role can read, encrypted by the app
-- (AES-256-GCM, key in ENCRYPTION_KEY) before they reach the database.

create table public.shopify_connections (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  shop_domain text not null check (shop_domain ~ '^[a-z0-9][a-z0-9-]*\.myshopify\.com$'),
  shop_name text,
  shopify_shop_gid text,
  currency text check (char_length(currency) = 3),
  scopes text[] not null default '{}',
  api_version text,
  status text not null default 'pending'
    check (status in ('pending', 'active', 'reauth_required', 'disconnected', 'uninstalled')),
  installed_at timestamptz,
  validated_at timestamptz,
  last_sync_at timestamptz,
  last_sync_status text check (last_sync_status in ('running', 'succeeded', 'partial', 'failed')),
  last_error text,
  disconnected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- "Connected" is only ever shown after the token was validated against the API.
  constraint shopify_active_requires_validation check (status <> 'active' or validated_at is not null)
);

-- One live connection per business, and a shop can be live for only one business.
create unique index shopify_connections_one_live_per_business
  on public.shopify_connections (business_id) where status in ('pending', 'active', 'reauth_required');
create unique index shopify_connections_one_live_per_shop
  on public.shopify_connections (shop_domain) where status in ('pending', 'active', 'reauth_required');

create trigger shopify_connections_set_updated_at before update on public.shopify_connections
  for each row execute function public.set_updated_at();

create table public.shopify_credentials (
  connection_id uuid primary key references public.shopify_connections (id) on delete cascade,
  business_id uuid not null references public.businesses (id) on delete cascade,
  access_token_enc text not null,
  access_token_expires_at timestamptz,
  refresh_token_enc text,
  refresh_token_expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create trigger shopify_credentials_set_updated_at before update on public.shopify_credentials
  for each row execute function public.set_updated_at();

-- Short-lived OAuth state (CSRF protection for the install/authorize redirect).
create table public.shopify_oauth_states (
  state_hash text primary key,
  business_id uuid not null references public.businesses (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  shop_domain text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------
-- array_to_string is only STABLE; for text[] it is safe to treat as immutable,
-- which generated search columns require.
create or replace function public.tags_to_text(p_tags text[])
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$ select array_to_string(p_tags, ' ') $$;

create table public.products (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  shopify_connection_id uuid references public.shopify_connections (id) on delete set null,
  shopify_gid text not null,
  title text not null,
  handle text,
  description text,
  product_type text,
  vendor text,
  tags text[] not null default '{}',
  status text not null default 'active' check (status in ('active', 'draft', 'archived', 'unlisted')),
  online_store_url text,
  featured_image_url text,
  images jsonb not null default '[]'::jsonb,
  options jsonb not null default '[]'::jsonb,
  price_min numeric(12, 2),
  price_max numeric(12, 2),
  currency text,
  total_inventory integer,
  tracks_inventory boolean,
  shopify_updated_at timestamptz,
  synced_at timestamptz not null default now(),
  deleted_at timestamptz,
  search tsvector generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(product_type, '') || ' ' || coalesce(vendor, '') || ' ' ||
                                     public.tags_to_text(tags)), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C')
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, shopify_gid)
);

create index products_business_idx on public.products (business_id) where deleted_at is null;
create index products_search_idx on public.products using gin (search);

create trigger products_set_updated_at before update on public.products
  for each row execute function public.set_updated_at();

create table public.product_variants (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  shopify_gid text not null,
  title text not null,
  sku text,
  price numeric(12, 2),
  compare_at_price numeric(12, 2),
  selected_options jsonb not null default '[]'::jsonb,
  available_for_sale boolean,
  -- NULL means "not known": the AI must not claim stock it cannot verify.
  inventory_quantity integer,
  inventory_tracked boolean,
  image_url text,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, shopify_gid)
);

create index product_variants_product_idx on public.product_variants (product_id);

create trigger product_variants_set_updated_at before update on public.product_variants
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Customers — only what the product needs (no phone, no addresses).
-- ---------------------------------------------------------------------------
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  shopify_gid text,
  email text check (email is null or email = lower(email)),
  name text,
  orders_count integer,
  total_spent numeric(12, 2),
  currency text,
  lead_status text not null default 'none'
    check (lead_status in ('none', 'new', 'contacted', 'qualified', 'converted', 'lost')),
  support_notes text check (char_length(support_notes) <= 10000),
  preferred_channel text check (preferred_channel in ('email', 'sms', 'chat')),
  marketing_opted_out_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz,
  redacted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index customers_business_gid_idx on public.customers (business_id, shopify_gid) where shopify_gid is not null;
create unique index customers_business_email_idx on public.customers (business_id, email) where email is not null;

create trigger customers_set_updated_at before update on public.customers
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------------
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  shopify_gid text not null,
  customer_id uuid references public.customers (id) on delete set null,
  name text not null,                       -- e.g. "#1001"
  email text check (email is null or email = lower(email)), -- used only for verification
  processed_at timestamptz,
  financial_status text,
  fulfillment_status text,
  display_status text,
  cancelled_at timestamptz,
  cancel_reason text,
  currency text,
  total_price numeric(12, 2),
  subtotal_price numeric(12, 2),
  status_page_url text,
  shopify_updated_at timestamptz,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, shopify_gid)
);

create index orders_business_name_idx on public.orders (business_id, name);
create index orders_business_processed_idx on public.orders (business_id, processed_at desc);
create index orders_customer_idx on public.orders (customer_id);

create trigger orders_set_updated_at before update on public.orders
  for each row execute function public.set_updated_at();

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  order_id uuid not null references public.orders (id) on delete cascade,
  shopify_gid text not null,
  product_id uuid references public.products (id) on delete set null,
  variant_id uuid references public.product_variants (id) on delete set null,
  title text not null,
  variant_title text,
  sku text,
  quantity integer not null check (quantity >= 0),
  unit_price numeric(12, 2),
  image_url text,
  created_at timestamptz not null default now(),
  unique (business_id, shopify_gid)
);

create index order_items_order_idx on public.order_items (order_id);

create table public.fulfillments (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  order_id uuid not null references public.orders (id) on delete cascade,
  shopify_gid text not null,
  status text,
  display_status text,
  tracking_company text,
  tracking_number text,
  tracking_url text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  estimated_delivery_at timestamptz,
  shopify_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, shopify_gid)
);

create index fulfillments_order_idx on public.fulfillments (order_id);

create trigger fulfillments_set_updated_at before update on public.fulfillments
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Inbound webhooks (Shopify, Stripe). Deduplicated on the provider's
-- delivery/event ID so a duplicate delivery is recorded once and processed once.
-- ---------------------------------------------------------------------------
create table public.integration_webhooks (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references public.businesses (id) on delete cascade,
  provider text not null check (provider in ('shopify', 'stripe')),
  topic text not null,
  external_id text not null,
  shop_domain text,
  payload jsonb not null,
  status text not null default 'received' check (status in ('received', 'processing', 'processed', 'failed', 'ignored')),
  attempts integer not null default 0,
  last_error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider, external_id)
);

create index integration_webhooks_status_idx on public.integration_webhooks (status, received_at);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.shopify_connections enable row level security;
alter table public.shopify_credentials enable row level security;
alter table public.shopify_oauth_states enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.fulfillments enable row level security;
alter table public.integration_webhooks enable row level security;

create policy shopify_connections_select_member on public.shopify_connections for select to authenticated
  using (public.is_business_member(business_id));
create policy products_select_member on public.products for select to authenticated
  using (public.is_business_member(business_id));
create policy product_variants_select_member on public.product_variants for select to authenticated
  using (public.is_business_member(business_id));
create policy customers_select_member on public.customers for select to authenticated
  using (public.is_business_member(business_id));
create policy customers_update_member on public.customers for update to authenticated
  using (public.is_business_member(business_id)) with check (public.is_business_member(business_id));
create policy orders_select_member on public.orders for select to authenticated
  using (public.is_business_member(business_id));
create policy order_items_select_member on public.order_items for select to authenticated
  using (public.is_business_member(business_id));
create policy fulfillments_select_member on public.fulfillments for select to authenticated
  using (public.is_business_member(business_id));

revoke all on public.shopify_connections, public.shopify_credentials, public.shopify_oauth_states,
  public.products, public.product_variants, public.customers, public.orders, public.order_items,
  public.fulfillments, public.integration_webhooks
  from anon;
revoke all on public.shopify_credentials, public.shopify_oauth_states, public.integration_webhooks
  from authenticated;
revoke insert, update, delete on public.shopify_connections, public.products, public.product_variants,
  public.orders, public.order_items, public.fulfillments
  from authenticated;
revoke insert, delete on public.customers from authenticated;
revoke update on public.customers from authenticated;
grant update (lead_status, support_notes) on public.customers to authenticated;

-- ============================================================
-- 20260924000400_conversations_support.sql
-- ============================================================
-- Mairo Assist — conversations, verification, support tickets, approvals,
-- AI tool audit trail.

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  customer_id uuid references public.customers (id) on delete set null,
  -- Opaque, random per-browser identifier issued by the widget. Not PII.
  visitor_id text check (char_length(visitor_id) <= 100),
  channel text not null default 'widget' check (channel in ('widget', 'preview')),
  status text not null default 'new'
    check (status in ('new', 'ai_handling', 'needs_attention', 'human_handling', 'resolved')),
  -- Who answers the customer right now. When 'human', the AI never replies.
  handled_by text not null default 'ai' check (handled_by in ('ai', 'human')),
  assigned_user_id uuid references public.users (id) on delete set null,
  -- Set only after the one-time verification succeeds; scoped to this conversation.
  verified_customer_id uuid references public.customers (id) on delete set null,
  verified_until timestamptz,
  subject text check (char_length(subject) <= 200),
  message_count integer not null default 0,
  last_message_at timestamptz,
  resolved_at timestamptz,
  escalated_at timestamptz,
  content_redacted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_human_status check (
    handled_by = 'ai' or status in ('human_handling', 'needs_attention', 'resolved')
  )
);

create index conversations_business_status_idx on public.conversations (business_id, status, last_message_at desc);
create index conversations_business_created_idx on public.conversations (business_id, created_at desc);
create index conversations_customer_idx on public.conversations (customer_id);

create trigger conversations_set_updated_at before update on public.conversations
  for each row execute function public.set_updated_at();

create table public.conversation_messages (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  sender_type text not null check (sender_type in ('customer', 'ai', 'human', 'system')),
  sender_user_id uuid references public.users (id) on delete set null,
  content text not null check (char_length(content) <= 8000),
  -- Structured attachments shown in the widget, e.g. product cards.
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments) = 'array'),
  -- Merchant-facing: which knowledge/catalog sources informed an AI answer.
  sources jsonb not null default '[]'::jsonb check (jsonb_typeof(sources) = 'array'),
  created_at timestamptz not null default now(),
  constraint messages_human_sender check (sender_type <> 'human' or sender_user_id is not null)
);

create index conversation_messages_conversation_idx on public.conversation_messages (conversation_id, created_at);

-- Messages must belong to the same business as their conversation.
create or replace function public.check_message_business()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.conversations c where c.id = new.conversation_id and c.business_id = new.business_id
  ) then
    raise exception 'Message business does not match conversation business' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger conversation_messages_same_business before insert on public.conversation_messages
  for each row execute function public.check_message_business();

-- One-time order verification codes. Only hashes are stored.
create table public.order_verifications (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  customer_id uuid references public.customers (id) on delete cascade,
  code_hash text not null,
  attempts integer not null default 0,
  max_attempts integer not null default 5,
  expires_at timestamptz not null,
  verified_at timestamptz,
  created_at timestamptz not null default now()
);

create index order_verifications_conversation_idx on public.order_verifications (conversation_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Support tickets and merchant approval requests
-- ---------------------------------------------------------------------------
create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  conversation_id uuid references public.conversations (id) on delete set null,
  customer_id uuid references public.customers (id) on delete set null,
  order_id uuid references public.orders (id) on delete set null,
  type text not null check (type in ('general', 'return', 'exchange', 'refund', 'cancellation',
                                     'shipping', 'address_change', 'escalation', 'other')),
  status text not null default 'open' check (status in ('open', 'pending', 'resolved', 'closed')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  subject text not null check (char_length(subject) <= 200),
  description text check (char_length(description) <= 5000),
  assigned_user_id uuid references public.users (id) on delete set null,
  created_by_type text not null check (created_by_type in ('ai', 'human', 'customer', 'system')),
  created_by_user_id uuid references public.users (id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index support_tickets_business_status_idx on public.support_tickets (business_id, status, created_at desc);

create trigger support_tickets_set_updated_at before update on public.support_tickets
  for each row execute function public.set_updated_at();

-- A customer request is never permission. Every write operation on an order
-- waits here until an authorized merchant decides, and records exactly what
-- was done and whether Shopify confirmed it.
create table public.order_action_requests (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  ticket_id uuid references public.support_tickets (id) on delete set null,
  conversation_id uuid references public.conversations (id) on delete set null,
  customer_id uuid references public.customers (id) on delete set null,
  order_id uuid references public.orders (id) on delete set null,
  action_type text not null check (action_type in ('return', 'exchange', 'refund', 'cancellation', 'address_change')),
  status text not null default 'awaiting_approval' check (status in (
    'awaiting_approval', 'approved', 'rejected', 'executing', 'completed', 'failed', 'manual_required'
  )),
  request_details jsonb not null default '{}'::jsonb,
  verified_availability jsonb,
  decided_by uuid references public.users (id) on delete set null,
  decided_at timestamptz,
  decision_note text check (char_length(decision_note) <= 2000),
  executed_action text,
  execution_result jsonb,
  shopify_confirmed boolean not null default false,
  -- Guards against executing the same operation twice.
  idempotency_key text not null unique default gen_random_uuid()::text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint action_requests_decision check (
    status in ('awaiting_approval') or decided_by is not null or status in ('failed', 'manual_required')
  ),
  constraint action_requests_completed_confirmed check (status <> 'completed' or shopify_confirmed)
);

create index order_action_requests_business_status_idx
  on public.order_action_requests (business_id, status, created_at desc);

create trigger order_action_requests_set_updated_at before update on public.order_action_requests
  for each row execute function public.set_updated_at();

-- Audit trail of every tool the AI asked to run (inputs are redacted by the app).
create table public.ai_tool_executions (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  conversation_id uuid references public.conversations (id) on delete set null,
  message_id uuid references public.conversation_messages (id) on delete set null,
  tool_name text not null check (char_length(tool_name) <= 80),
  input jsonb not null default '{}'::jsonb,
  output_summary jsonb,
  status text not null check (status in ('success', 'denied', 'invalid_input', 'error')),
  error_code text,
  duration_ms integer,
  created_at timestamptz not null default now()
);

create index ai_tool_executions_business_idx on public.ai_tool_executions (business_id, created_at desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.conversations enable row level security;
alter table public.conversation_messages enable row level security;
alter table public.order_verifications enable row level security;
alter table public.support_tickets enable row level security;
alter table public.order_action_requests enable row level security;
alter table public.ai_tool_executions enable row level security;

create policy conversations_select_member on public.conversations for select to authenticated
  using (public.is_business_member(business_id));
create policy messages_select_member on public.conversation_messages for select to authenticated
  using (public.is_business_member(business_id));
create policy tickets_select_member on public.support_tickets for select to authenticated
  using (public.is_business_member(business_id));
create policy action_requests_select_member on public.order_action_requests for select to authenticated
  using (public.is_business_member(business_id));
create policy tool_executions_select_manager on public.ai_tool_executions for select to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));

-- All writes to conversations, messages, tickets and approvals go through the
-- server, which checks role permissions, takeover state and idempotency.
revoke all on public.conversations, public.conversation_messages, public.order_verifications,
  public.support_tickets, public.order_action_requests, public.ai_tool_executions
  from anon;
revoke all on public.order_verifications from authenticated;
revoke insert, update, delete on public.conversations, public.conversation_messages,
  public.support_tickets, public.order_action_requests, public.ai_tool_executions
  from authenticated;

-- Activity feed rows point at real records (kept if the record is removed).
alter table public.activity_logs
  add constraint activity_logs_conversation_fk foreign key (conversation_id)
    references public.conversations (id) on delete set null,
  add constraint activity_logs_customer_fk foreign key (customer_id)
    references public.customers (id) on delete set null,
  add constraint activity_logs_order_fk foreign key (order_id)
    references public.orders (id) on delete set null;

-- ============================================================
-- 20260924000500_growth_billing_analytics.sql
-- ============================================================
-- Mairo Assist — leads, consent, follow-ups, analytics, subscriptions, usage.

-- ---------------------------------------------------------------------------
-- Leads and consent. Outbound follow-up is NOT active in v1: these tables
-- record what a merchant needs to decide eligibility later, and nothing
-- sends messages without a granted, unrevoked consent for that channel.
-- ---------------------------------------------------------------------------
create table public.leads (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  customer_id uuid references public.customers (id) on delete set null,
  conversation_id uuid references public.conversations (id) on delete set null,
  name text check (char_length(name) <= 120),
  email text check (email is null or (email = lower(email) and char_length(email) <= 320)),
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'converted', 'lost')),
  source text not null default 'chat' check (source in ('chat', 'manual', 'import')),
  interest text check (char_length(interest) <= 1000),
  notes text check (char_length(notes) <= 5000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index leads_business_created_idx on public.leads (business_id, created_at desc);

create trigger leads_set_updated_at before update on public.leads
  for each row execute function public.set_updated_at();

create table public.customer_consents (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  customer_id uuid references public.customers (id) on delete cascade,
  lead_id uuid references public.leads (id) on delete cascade,
  channel text not null check (channel in ('email', 'sms')),
  purpose text not null check (purpose in ('marketing', 'follow_up', 'transactional')),
  status text not null check (status in ('granted', 'revoked')),
  source text not null check (char_length(source) <= 120),  -- e.g. "widget_checkbox_v1"
  evidence jsonb not null default '{}'::jsonb,               -- wording shown, timestamp, page
  granted_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  constraint consents_subject check (customer_id is not null or lead_id is not null)
);

create index customer_consents_lookup_idx on public.customer_consents (business_id, customer_id, channel, purpose);

create table public.lead_follow_ups (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  lead_id uuid not null references public.leads (id) on delete cascade,
  channel text not null check (channel in ('email', 'sms', 'manual')),
  reason text not null check (reason in ('product_interest', 'abandoned_checkout', 'sales_request', 'other')),
  status text not null default 'planned' check (status in ('planned', 'sent', 'skipped', 'failed', 'cancelled')),
  skip_reason text,
  scheduled_for timestamptz,
  sent_at timestamptz,
  created_by uuid references public.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index lead_follow_ups_lead_idx on public.lead_follow_ups (lead_id);

-- ---------------------------------------------------------------------------
-- Analytics events: actual system activity only. Properties must not carry
-- raw customer personal data (enforced by the app's event writer).
--
-- Attribution rule (documented in docs/ANALYTICS.md): an "ai_attributed_order"
-- event is written only when an order is linked to a conversation in which
-- the AI recommended a product that appears in that order, and the order was
-- placed within the attribution window after that recommendation.
-- ---------------------------------------------------------------------------
create table public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  event_type text not null check (event_type in (
    'conversation_started', 'conversation_resolved_by_ai', 'conversation_escalated',
    'product_recommended', 'product_link_clicked', 'lead_captured', 'order_lookup',
    'return_request_created', 'exchange_request_created', 'refund_request_created',
    'cancellation_request_created', 'ticket_created', 'ai_attributed_order'
  )),
  conversation_id uuid references public.conversations (id) on delete set null,
  product_id uuid references public.products (id) on delete set null,
  order_id uuid references public.orders (id) on delete set null,
  value numeric(12, 2),
  currency text,
  properties jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  -- Makes event writes idempotent (e.g. one attributed-order event per order).
  dedupe_key text,
  unique (business_id, dedupe_key)
);

create index analytics_events_business_type_time_idx on public.analytics_events (business_id, event_type, occurred_at desc);
create index analytics_events_business_time_idx on public.analytics_events (business_id, occurred_at desc);

-- ---------------------------------------------------------------------------
-- Billing. One subscription row per business; exactly one billing provider
-- at a time so a business is never charged twice for the same plan.
-- ---------------------------------------------------------------------------
create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null unique references public.businesses (id) on delete cascade,
  plan_key text not null check (plan_key in ('starter', 'growth', 'pro', 'enterprise')),
  status text not null check (status in ('trialing', 'active', 'past_due', 'canceled', 'incomplete', 'paused')),
  provider text not null check (provider in ('stripe', 'shopify', 'manual')),
  provider_customer_id text,
  provider_subscription_id text,
  price_cents integer check (price_cents >= 0),
  currency text not null default 'usd',
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  trial_ends_at timestamptz,
  canceled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_subscription_id)
);

create trigger subscriptions_set_updated_at before update on public.subscriptions
  for each row execute function public.set_updated_at();

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  provider text not null check (provider in ('stripe', 'shopify', 'manual')),
  provider_invoice_id text not null,
  amount_cents integer not null,
  currency text not null,
  status text not null check (status in ('draft', 'open', 'paid', 'uncollectible', 'void')),
  hosted_url text,
  period_start timestamptz,
  period_end timestamptz,
  created_at timestamptz not null default now(),
  unique (provider, provider_invoice_id)
);

create index invoices_business_idx on public.invoices (business_id, created_at desc);

-- ---------------------------------------------------------------------------
-- AI usage. usage_records is one row per model request; usage_counters is the
-- per-billing-period rollup that allowance checks read (cheap, O(1)).
-- ---------------------------------------------------------------------------
create table public.usage_records (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  conversation_id uuid references public.conversations (id) on delete set null,
  kind text not null check (kind in ('chat_completion', 'embedding', 'preview')),
  model text not null,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  cached_input_tokens integer not null default 0 check (cached_input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  estimated_cost_usd numeric(12, 6) not null default 0,
  provider_cost_usd numeric(12, 6),
  provider_request_id text,
  created_at timestamptz not null default now()
);

create index usage_records_business_time_idx on public.usage_records (business_id, created_at desc);

create table public.usage_counters (
  business_id uuid not null references public.businesses (id) on delete cascade,
  period_start date not null,
  conversations integer not null default 0,
  model_requests integer not null default 0,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  estimated_cost_usd numeric(14, 6) not null default 0,
  limit_warning_sent_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (business_id, period_start)
);

-- Record one model request and roll it into the period counter atomically.
create or replace function public.record_ai_usage(
  p_business_id uuid,
  p_conversation_id uuid,
  p_kind text,
  p_model text,
  p_input_tokens integer,
  p_cached_input_tokens integer,
  p_output_tokens integer,
  p_estimated_cost_usd numeric,
  p_period_start date,
  p_provider_request_id text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.usage_records (business_id, conversation_id, kind, model, input_tokens,
    cached_input_tokens, output_tokens, estimated_cost_usd, provider_request_id)
  values (p_business_id, p_conversation_id, p_kind, p_model, p_input_tokens, p_cached_input_tokens,
    p_output_tokens, p_estimated_cost_usd, p_provider_request_id);

  insert into public.usage_counters as c (business_id, period_start, model_requests, input_tokens,
    output_tokens, estimated_cost_usd)
  values (p_business_id, p_period_start, 1, p_input_tokens, p_output_tokens, p_estimated_cost_usd)
  on conflict (business_id, period_start) do update set
    model_requests = c.model_requests + 1,
    input_tokens = c.input_tokens + excluded.input_tokens,
    output_tokens = c.output_tokens + excluded.output_tokens,
    estimated_cost_usd = c.estimated_cost_usd + excluded.estimated_cost_usd,
    updated_at = now();
end;
$$;

create or replace function public.increment_conversation_usage(p_business_id uuid, p_period_start date)
returns integer
language sql
security definer
set search_path = ''
as $$
  insert into public.usage_counters as c (business_id, period_start, conversations)
  values (p_business_id, p_period_start, 1)
  on conflict (business_id, period_start) do update set conversations = c.conversations + 1, updated_at = now()
  returning conversations;
$$;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.leads enable row level security;
alter table public.customer_consents enable row level security;
alter table public.lead_follow_ups enable row level security;
alter table public.analytics_events enable row level security;
alter table public.subscriptions enable row level security;
alter table public.invoices enable row level security;
alter table public.usage_records enable row level security;
alter table public.usage_counters enable row level security;

create policy leads_select_member on public.leads for select to authenticated
  using (public.is_business_member(business_id));
create policy leads_update_member on public.leads for update to authenticated
  using (public.is_business_member(business_id)) with check (public.is_business_member(business_id));
create policy consents_select_member on public.customer_consents for select to authenticated
  using (public.is_business_member(business_id));
create policy follow_ups_select_member on public.lead_follow_ups for select to authenticated
  using (public.is_business_member(business_id));
create policy analytics_select_manager on public.analytics_events for select to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));
-- Billing is visible to owners and admins; only owners can change it (via the server).
create policy subscriptions_select_manager on public.subscriptions for select to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));
create policy invoices_select_owner on public.invoices for select to authenticated
  using (public.has_business_role(business_id, array['owner']));
create policy usage_records_select_manager on public.usage_records for select to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));
create policy usage_counters_select_manager on public.usage_counters for select to authenticated
  using (public.has_business_role(business_id, array['owner', 'admin']));

revoke all on public.leads, public.customer_consents, public.lead_follow_ups, public.analytics_events,
  public.subscriptions, public.invoices, public.usage_records, public.usage_counters
  from anon;
revoke insert, update, delete on public.customer_consents, public.lead_follow_ups, public.analytics_events,
  public.subscriptions, public.invoices, public.usage_records, public.usage_counters
  from authenticated;
revoke insert, delete on public.leads from authenticated;
revoke update on public.leads from authenticated;
grant update (status, notes) on public.leads to authenticated;

revoke execute on function public.record_ai_usage(uuid, uuid, text, text, integer, integer, integer, numeric, date, text)
  from public, anon, authenticated;
revoke execute on function public.increment_conversation_usage(uuid, date) from public, anon, authenticated;
grant execute on function public.record_ai_usage(uuid, uuid, text, text, integer, integer, integer, numeric, date, text)
  to service_role;
grant execute on function public.increment_conversation_usage(uuid, date) to service_role;

-- Plan lookup any member can use for feature gating (no billing details exposed).
create or replace function public.business_plan(p_business_id uuid)
returns table (plan_key text, status text)
language sql
stable
security definer
set search_path = ''
as $$
  select s.plan_key, s.status
  from public.subscriptions s
  where s.business_id = p_business_id and public.is_business_member(p_business_id);
$$;

revoke execute on function public.business_plan(uuid) from public, anon;
grant execute on function public.business_plan(uuid) to authenticated;

-- ============================================================
-- 20260925000100_phase2_ai_conversations.sql
-- ============================================================
-- Mairo Assist — Phase 2: AI conversations, preview, knowledge retrieval,
-- retention.

-- Preview (owner test) conversations belong to the team member who ran them.
alter table public.conversations
  add column preview_user_id uuid references public.users (id) on delete cascade,
  add constraint conversations_preview_owner check (channel <> 'preview' or preview_user_id is not null);

create index conversations_preview_idx on public.conversations (business_id, preview_user_id) where channel = 'preview';

-- Keep message_count / last_message_at in step with the messages table.
create or replace function public.bump_conversation_on_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.conversations
  set message_count = message_count + 1,
      last_message_at = new.created_at,
      status = case when status = 'new' and new.sender_type = 'ai' then 'ai_handling' else status end
  where id = new.conversation_id;
  return new;
end;
$$;

create trigger conversation_messages_bump after insert on public.conversation_messages
  for each row execute function public.bump_conversation_on_message();

-- Which tools ran for an AI message (names only; details live in ai_tool_executions).
alter table public.conversation_messages
  add column tool_names text[] not null default '{}';

-- ---------------------------------------------------------------------------
-- Knowledge retrieval. Matches ANY meaningful word of the query (a customer
-- question rarely contains every word of the policy), ranked by relevance.
-- Always scoped to one business; callable by the server only.
-- ---------------------------------------------------------------------------
create or replace function public.search_knowledge_chunks(p_business_id uuid, p_query text, p_limit integer default 5)
returns table (
  chunk_id uuid,
  document_id uuid,
  title text,
  category text,
  content text,
  rank real
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_query tsquery;
begin
  select to_tsquery('english', string_agg(lexeme, ' | '))
  into v_query
  from unnest(tsvector_to_array(to_tsvector('english', left(coalesce(p_query, ''), 500)))) as lexeme;

  if v_query is null then
    return;
  end if;

  return query
  select c.id, d.id, d.title, d.category, c.content, ts_rank_cd(c.tsv, v_query) as rank
  from public.knowledge_chunks c
  join public.knowledge_documents d on d.id = c.document_id
  where c.business_id = p_business_id
    and d.business_id = p_business_id
    and d.status = 'ready'
    and c.tsv @@ v_query
  order by rank desc, d.updated_at desc
  limit greatest(1, least(p_limit, 10));
end;
$$;

revoke execute on function public.search_knowledge_chunks(uuid, text, integer) from public, anon, authenticated;
grant execute on function public.search_knowledge_chunks(uuid, text, integer) to service_role;

-- ---------------------------------------------------------------------------
-- Retention: delete conversations whose last activity is older than the
-- business's configured retention period. Preview chats are kept 7 days.
-- ---------------------------------------------------------------------------
create or replace function public.purge_expired_conversations()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  delete from public.conversations c
  using public.business_settings s
  where s.business_id = c.business_id
    and coalesce(c.last_message_at, c.created_at) <
        now() - make_interval(days => case when c.channel = 'preview' then 7 else s.conversation_retention_days end);
  get diagnostics v_count = row_count;
  delete from public.rate_limits where window_start < now() - interval '2 days';
  return v_count;
end;
$$;

revoke execute on function public.purge_expired_conversations() from public, anon, authenticated;
grant execute on function public.purge_expired_conversations() to service_role;

-- Preview conversations are private to the person testing.
drop policy conversations_select_member on public.conversations;
create policy conversations_select_member on public.conversations for select to authenticated
  using (public.is_business_member(business_id) and (channel <> 'preview' or preview_user_id = (select auth.uid())));

-- When the owner last changed the draft (name or configuration). Lets the UI
-- tell whether the latest draft has been tried in the preview.
alter table public.ai_employees add column draft_saved_at timestamptz not null default now();

create or replace function public.touch_ai_draft()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.draft_config is distinct from old.draft_config or new.name is distinct from old.name then
    new.draft_saved_at := now();
  end if;
  return new;
end;
$$;

create trigger ai_employees_touch_draft before update on public.ai_employees
  for each row execute function public.touch_ai_draft();
