#!/usr/bin/env bash
# Concatenates every migration into supabase/setup_all.sql, a single file that
# can be pasted into the Supabase SQL editor for a brand-new project.
# Re-run after adding a migration. For existing projects apply only new files.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- Mairo Assist: complete database setup for a NEW Supabase project."
  echo "-- Generated by scripts/build-setup-sql.sh from supabase/migrations/. Do not edit by hand."
  echo "-- Paste this whole file into Supabase → SQL Editor and click Run, once."
  for f in supabase/migrations/*.sql; do
    echo; echo "-- ============================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================"
    cat "$f"
  done
} > supabase/setup_all.sql
echo "wrote supabase/setup_all.sql"
