"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { NotificationSeverity } from "@/generated/prisma/enums";
import { markAllReadAction } from "@/lib/actions/notification-actions";

// The bell, and the short list behind it.
//
// Deliberately not a live feed. The count and the rows are rendered by the
// server on each navigation, which for a product whose notifications are
// generated by a daily sweep is exactly as fresh as the data is — polling
// would cost a request a minute to tell somebody the same thing.
//
// The badge shows unread, not total. A number that never goes down is a number
// people stop reading.

export type BellItem = {
  id: string;
  title: string;
  body: string;
  severity: NotificationSeverity;
  href: string | null;
  actionLabel: string | null;
  createdAt: string;
  read: boolean;
};

const TONE: Record<NotificationSeverity, string> = {
  INFO: "var(--color-blue-bright, #6c9eff)",
  OPPORTUNITY: "rgb(52,211,153)",
  WARNING: "rgb(251,191,36)",
};

export function NotificationBell({ items, unread }: { items: BellItem[]; unread: number }) {
  const pathname = usePathname();
  // Where the panel was opened from, rather than a boolean. Navigating away
  // has to close it — a panel left hanging over the page it just linked to is
  // the most obvious way this breaks — and deriving that at render is what
  // keeps it out of an effect, which the lint rule rightly objects to.
  const [openedAt, setOpenedAt] = useState<string | null>(null);
  const open = openedAt === pathname;
  const setOpen = (next: boolean) => setOpenedAt(next ? pathname : null);
  const wrap = useRef<HTMLDivElement>(null);

  // Close on a click outside and on Escape, as every other overlay does.
  useEffect(() => {
    if (!open) return;
    // setOpenedAt directly rather than the setOpen helper: the helper closes
    // over `pathname`, which would put it in this effect's dependencies and
    // re-bind both listeners on every navigation for no reason.
    const onClick = (e: MouseEvent) => {
      if (wrap.current && !wrap.current.contains(e.target as Node)) setOpenedAt(null);
    };
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && setOpenedAt(null);
    document.addEventListener("mousedown", onClick);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onClick);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  return (
    <div ref={wrap} className="relative">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        aria-label={unread > 0 ? `Notifications, ${unread} unread` : "Notifications"}
        aria-expanded={open}
        className="relative flex h-9 w-9 items-center justify-center rounded-full text-muted transition-colors hover:bg-white/[0.06] hover:text-white"
      >
        <svg viewBox="0 0 20 20" className="h-[18px] w-[18px]" fill="none" aria-hidden>
          <path
            d="M10 3.2a4.6 4.6 0 0 0-4.6 4.6c0 3-1 4.2-1.5 4.7a.5.5 0 0 0 .35.86h11.5a.5.5 0 0 0 .35-.86c-.5-.5-1.5-1.7-1.5-4.7A4.6 4.6 0 0 0 10 3.2Z"
            stroke="currentColor"
            strokeWidth="1.4"
            strokeLinejoin="round"
          />
          <path d="M8.4 16.2a1.8 1.8 0 0 0 3.2 0" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
        </svg>
        {unread > 0 && (
          <span
            aria-hidden
            className="absolute right-1 top-1 flex h-4 min-w-4 items-center justify-center rounded-full px-1 text-[9px] font-medium text-white"
            style={{ backgroundImage: "var(--mairo-ramp)" }}
          >
            {unread > 9 ? "9+" : unread}
          </span>
        )}
      </button>

      {open && (
        <div
          role="dialog"
          aria-label="Notifications"
          className="absolute right-0 top-11 z-50 w-[min(360px,calc(100vw-2rem))] overflow-hidden rounded-2xl border"
          style={{
            borderColor: "var(--mairo-line-lit)",
            background: "rgba(8,13,30,0.98)",
            boxShadow: "var(--mairo-glow-lift)",
          }}
        >
          <div
            className="flex items-center justify-between border-b px-4 py-3"
            style={{ borderColor: "var(--mairo-line)" }}
          >
            <p className="text-[13px] font-medium text-white">Notifications</p>
            {unread > 0 && (
              <form action={markAllReadAction}>
                <button type="submit" className="text-[11.5px] text-blue-bright hover:text-white">
                  Mark all read
                </button>
              </form>
            )}
          </div>

          <div className="max-h-[min(420px,60vh)] overflow-y-auto">
            {items.length === 0 ? (
              <p className="px-4 py-8 text-center text-[12.5px] leading-relaxed text-faint">
                Nothing yet. MAIRO tells you here when something needs you — a campaign
                spending without results, a platform doing better than another, an account
                that has disconnected.
              </p>
            ) : (
              <ul>
                {items.map((n) => {
                  const inner = (
                    <>
                      <span className="flex items-start gap-2.5">
                        <span
                          aria-hidden
                          className="mt-[6px] h-1.5 w-1.5 shrink-0 rounded-full"
                          style={{ background: n.read ? "transparent" : TONE[n.severity] }}
                        />
                        <span className="min-w-0">
                          <span className="block text-[12.5px] font-medium leading-snug text-white">
                            {n.title}
                          </span>
                          <span className="mt-1 block text-[11.5px] leading-relaxed text-muted">
                            {n.body}
                          </span>
                          <span className="mt-1.5 block text-[10.5px] text-faint">
                            {n.createdAt}
                            {n.actionLabel ? ` · ${n.actionLabel}` : ""}
                          </span>
                        </span>
                      </span>
                    </>
                  );
                  return (
                    <li key={n.id} className="border-b last:border-b-0" style={{ borderColor: "var(--mairo-line)" }}>
                      {n.href ? (
                        <Link href={n.href} className="block px-4 py-3 transition-colors hover:bg-white/[0.04]">
                          {inner}
                        </Link>
                      ) : (
                        <div className="px-4 py-3">{inner}</div>
                      )}
                    </li>
                  );
                })}
              </ul>
            )}
          </div>

          <div className="border-t px-4 py-2.5" style={{ borderColor: "var(--mairo-line)" }}>
            <Link href="/dashboard/notifications" className="text-[12px] text-blue-bright hover:text-white">
              See everything
            </Link>
          </div>
        </div>
      )}
    </div>
  );
}
