"use client";

import { useEffect, useRef } from "react";

// The photographic sky the marketing page sits in.
//
// This is a real rendered image, not code drawing a galaxy every frame. The
// panorama in /public/sky is generated by scripts/render-milky-way.py: four
// thousand pixels wide, with dust modelled as absorption, wavelength-dependent
// extinction, and about nine hundred thousand individual stars. Nothing on that
// list could be computed sixty times a second, and none of it needs to be —
// the sky does not change. It gets computed once, at build time, and the
// browser only ever moves it.
//
// That is the whole performance argument. Every animation here is a translate,
// which the compositor does on the GPU without repainting anything. The frame
// cost is the same whether the image holds nine hundred thousand stars or nine,
// so the detail is free once the image has downloaded — and it downloads in
// 144KB, because a dark sky compresses extremely well.
//
// The image is periodic along X. The noise it is built from is generated in
// Fourier space and the galactic plane is a sum of whole-cycle sinusoids, so
// the right edge continues into the left edge exactly. Two copies side by side,
// translated by exactly one copy's width, therefore pan forever with no seam
// and no jump at the loop point. Measured: the wrap-around column difference is
// 0.54/255 against 0.74 for a typical neighbouring column, so the join is
// smoother than the picture is.

const SRC = "/sky/milky-way-v1";

/**
 * One copy of the panorama.
 *
 * The `<picture>` does two negotiations at once. AVIF where it is supported and
 * WebP everywhere else, and — separately — the half-size image on phones and on
 * ordinary-density displays, the full one only where there are enough physical
 * pixels to show it. A 4096-wide image decodes to 37MB of bitmap whatever the
 * file size, which is not something to hand a phone for a background.
 *
 * Sized `max(100vw, 177.78vh)`: tall enough to fill the viewport at its own 16:9
 * ratio, and never narrower than the viewport, because two tiles only pan
 * seamlessly while one tile is at least a screen wide.
 */
function Tile({
  className,
  style,
  half = false,
}: {
  className?: string;
  style?: React.CSSProperties;
  /** Never load the 4K file. For places that show the sky small and dim. */
  half?: boolean;
}) {
  return (
    <picture>
      <source type="image/avif" media="(max-width: 900px)" srcSet={`${SRC}-half.avif`} />
      <source type="image/webp" media="(max-width: 900px)" srcSet={`${SRC}-half.webp`} />
      {!half && <source type="image/avif" srcSet={`${SRC}-half.avif 1x, ${SRC}.avif 2x`} />}
      {!half && <source type="image/webp" srcSet={`${SRC}-half.webp 1x, ${SRC}.webp 2x`} />}
      {half && <source type="image/avif" srcSet={`${SRC}-half.avif`} />}
      <img
        src={`${SRC}-half.webp`}
        alt=""
        aria-hidden
        decoding="async"
        className={className}
        style={style}
      />
    </picture>
  );
}

export function MilkyWay() {
  const parallax = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const node = parallax.current;
    if (!node) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    let raf = 0;
    let pointerX = 0;
    let pointerY = 0;
    let easedX = 0;
    let easedY = 0;
    let easedScroll = 0;

    function frame() {
      const scroll = window.scrollY;

      // Everything is eased towards its target rather than set to it. The
      // difference is the whole feeling of the thing: read straight, the sky
      // stops dead the instant the wheel does, which reads as a texture stuck
      // to the page. Eased, it carries on and settles, which reads as
      // something a long way away.
      easedX += (pointerX - easedX) * 0.035;
      easedY += (pointerY - easedY) * 0.035;
      easedScroll += (scroll - easedScroll) * 0.075;

      // Deliberately a fraction of the scroll distance. The sky moving a
      // fifteenth as far as the page is what puts it behind the page rather
      // than on it.
      const y = easedScroll * -0.068 + easedY * 14;
      const x = easedX * 22;

      // Written straight to the element, never through state. Sixty React
      // renders a second to move one background is the kind of thing that
      // makes a page feel heavy for no visible reason.
      node!.style.transform = `translate3d(${x.toFixed(2)}px, ${y.toFixed(2)}px, 0)`;
      raf = requestAnimationFrame(frame);
    }

    function onPointer(e: PointerEvent) {
      pointerX = (e.clientX / window.innerWidth) * 2 - 1;
      pointerY = (e.clientY / window.innerHeight) * 2 - 1;
    }

    raf = requestAnimationFrame(frame);
    window.addEventListener("pointermove", onPointer, { passive: true });

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("pointermove", onPointer);
    };
  }, []);

  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-[20] overflow-hidden bg-black">
      {/* Scaled slightly past the viewport so the parallax has somewhere to
          travel to without ever exposing an edge. */}
      <div
        ref={parallax}
        className="absolute -inset-y-[9%] inset-x-0 will-change-transform"
      >
        <div className="milkyway-pan flex h-full w-max">
          <Tile
            className="h-full max-w-none flex-none select-none object-cover"
            style={{ width: "max(100vw, 177.78vh)" }}
          />
          <Tile
            className="h-full max-w-none flex-none select-none object-cover"
            style={{ width: "max(100vw, 177.78vh)" }}
          />
        </div>
      </div>

      {/* Legibility, in two parts.

          A flat wash over the whole picture would be the easy way and it is the
          wrong one — it lifts the black sky to grey and the image stops reading
          as a photograph at all. Instead the darkening is a gradient that is
          strongest at the top and bottom, where the headlines and the footer
          sit, and lightest across the middle band, where the galaxy is and
          where there is the least type. */}
      <div className="absolute inset-0 bg-[linear-gradient(to_bottom,rgba(0,0,0,0.62)_0%,rgba(0,0,0,0.20)_28%,rgba(0,0,0,0.12)_52%,rgba(0,0,0,0.34)_78%,rgba(0,0,0,0.68)_100%)]" />
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(0,0,0,0)_0%,rgba(0,0,0,0.18)_58%,rgba(0,0,0,0.66)_100%)]" />

      <style>{`
        .milkyway-pan {
          /* One tile's width in 210 seconds. Slow enough that it never pulls
             the eye off the page, fast enough that it is obviously alive if
             you rest on it for a moment.

             translateX(-50%) of a two-tile row is exactly one tile, and the
             tiles are identical, so the loop point is not merely hidden — it
             is the same pixels. */
          animation: milkyway-pan 210s linear infinite;
          will-change: transform;
        }

        @keyframes milkyway-pan {
          from { transform: translate3d(0, 0, 0); }
          to   { transform: translate3d(-50%, 0, 0); }
        }

        /* A phone sees a 390px window onto a 1500px-wide panorama — about a
           quarter of it — and the quarter it would otherwise open on is the
           empty end. A negative delay starts the animation part-way through,
           so the first thing on screen is the galactic core rather than a
           minute and a half of quiet sky before it arrives. */
        @media (max-width: 900px) {
          .milkyway-pan { animation-delay: -77s; }
        }

        @media (prefers-reduced-motion: reduce) {
          .milkyway-pan { animation: none; }
        }
      `}</style>
    </div>
  );
}

/**
 * The same sky behind the signed-in app: one still frame, turned right down.
 *
 * Nothing moves and nothing is measured — it is an `<img>` and two gradients.
 * A dashboard is somewhere people work, and a backdrop that drifts competes
 * with the numbers they are trying to read; this keeps the identity and drops
 * the theatre. It also never loads the 4K file, because at this opacity behind
 * a table nobody is going to find the extra detail.
 */
export function MilkyWayStill({ opacity = 0.42 }: { opacity?: number } = {}) {
  return (
    <>
      <Tile
        half
        className="absolute inset-0 h-full w-full select-none object-cover"
        style={{ opacity }}
      />
      {/* Pulls the middle of the screen — where the work is — back towards
          flat, and leaves the sky readable only at the edges. */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_42%,rgba(10,10,14,0.80)_0%,rgba(10,10,14,0.52)_50%,rgba(10,10,14,0.14)_100%)]" />
    </>
  );
}
