"use client";

import { useEffect, useRef } from "react";

// The photographic sky the marketing page sits in.
//
// This is a real rendered image, not code drawing a galaxy every frame. The
// panorama in /public/sky is generated by scripts/render-milky-way.py: four
// thousand pixels wide, with dust modelled as absorption, wavelength-dependent
// extinction, and about nine hundred thousand individual stars. Nothing on that
// list could be computed sixty times a second, and none of it needs to be —
// the sky does not change. It gets computed once, at build time, and the
// browser only ever moves it.
//
// That is the whole performance argument. Every animation here is a translate,
// which the compositor does on the GPU without repainting anything. The frame
// cost is the same whether the image holds nine hundred thousand stars or nine,
// so the detail is free once the image has downloaded — and it downloads in
// 144KB, because a dark sky compresses extremely well.
//
// The image is periodic along X. The noise it is built from is generated in
// Fourier space and the galactic plane is a sum of whole-cycle sinusoids, so
// the right edge continues into the left edge exactly. Two copies side by side,
// translated by exactly one copy's width, therefore pan forever with no seam
// and no jump at the loop point. Measured: the wrap-around column difference is
// 0.54/255 against 0.74 for a typical neighbouring column, so the join is
// smoother than the picture is.

const SRC = "/sky/milky-way-v1";

/**
 * One copy of the panorama.
 *
 * The `<picture>` does two negotiations at once. AVIF where it is supported and
 * WebP everywhere else, and — separately — the half-size image on phones and on
 * ordinary-density displays, the full one only where there are enough physical
 * pixels to show it. A 4096-wide image decodes to 37MB of bitmap whatever the
 * file size, which is not something to hand a phone for a background.
 *
 * Sized `max(100vw, 177.78vh)`: tall enough to fill the viewport at its own 16:9
 * ratio, and never narrower than the viewport, because two tiles only pan
 * seamlessly while one tile is at least a screen wide.
 */
function Tile({
  className,
  style,
  half = false,
}: {
  className?: string;
  style?: React.CSSProperties;
  /** Never load the 4K file. For places that show the sky small and dim. */
  half?: boolean;
}) {
  return (
    <picture>
      <source type="image/avif" media="(max-width: 900px)" srcSet={`${SRC}-half.avif`} />
      <source type="image/webp" media="(max-width: 900px)" srcSet={`${SRC}-half.webp`} />
      {!half && <source type="image/avif" srcSet={`${SRC}-half.avif 1x, ${SRC}.avif 2x`} />}
      {!half && <source type="image/webp" srcSet={`${SRC}-half.webp 1x, ${SRC}.webp 2x`} />}
      {half && <source type="image/avif" srcSet={`${SRC}-half.avif`} />}
      <img
        src={`${SRC}-half.webp`}
        alt=""
        aria-hidden
        decoding="async"
        className={className}
        style={style}
      />
    </picture>
  );
}

export function MilkyWay() {
  const parallax = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const node = parallax.current;
    if (!node) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    let raf = 0;
    let pointerX = 0;
    let pointerY = 0;
    let easedX = 0;
    let easedY = 0;
    let easedScroll = 0;

    function frame() {
      const scroll = window.scrollY;

      // Everything is eased towards its target rather than set to it. The
      // difference is the whole feeling of the thing: read straight, the sky
      // stops dead the instant the wheel does, which reads as a texture stuck
      // to the page. Eased, it carries on and settles, which reads as
      // something a long way away.
      easedX += (pointerX - easedX) * 0.035;
      easedY += (pointerY - easedY) * 0.035;
      easedScroll += (scroll - easedScroll) * 0.075;

      // Deliberately a fraction of the scroll distance. The sky moving a
      // fifteenth as far as the page is what puts it behind the page rather
      // than on it.
      const y = easedScroll * -0.068 + easedY * 14;
      const x = easedX * 22;

      // Written straight to the element, never through state. Sixty React
      // renders a second to move one background is the kind of thing that
      // makes a page feel heavy for no visible reason.
      node!.style.transform = `translate3d(${x.toFixed(2)}px, ${y.toFixed(2)}px, 0)`;
      raf = requestAnimationFrame(frame);
    }

    function onPointer(e: PointerEvent) {
      pointerX = (e.clientX / window.innerWidth) * 2 - 1;
      pointerY = (e.clientY / window.innerHeight) * 2 - 1;
    }

    raf = requestAnimationFrame(frame);
    window.addEventListener("pointermove", onPointer, { passive: true });

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("pointermove", onPointer);
    };
  }, []);

  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-[20] overflow-hidden bg-black">
      {/* Scaled slightly past the viewport so the parallax has somewhere to
          travel to without ever exposing an edge. */}
      <div ref={parallax} className="milkyway-frame absolute inset-x-0 will-change-transform">
        <div className="milkyway-pan flex h-full w-max">
          <Tile className="milkyway-tile h-full max-w-none flex-none select-none object-cover" />
          <Tile className="milkyway-tile h-full max-w-none flex-none select-none object-cover" />
        </div>
      </div>

      {/* No legibility scrim here, deliberately.
          
          This component used to carry its own — a vertical veil and a vignette,
          written back when it was the whole background and had to protect the
          type by itself. It is not that any more: it only ever renders inside
          GalaxyBackground, which lays its own scrims over whatever is beneath
          it, and those are tuned against the live scene.
          
          So the two were stacking, and the sky the fallback showed came out at
          roughly half the brightness of the live one. Measured on the hero at
          1280x800: mean luminance 15 against the live scene's 29. That is what
          "the galaxy stopped showing" actually was — not a failure to render,
          but a fallback dimmed until it read as an empty black page. */}

      <style>{`
        /* Scaled slightly past the viewport so the parallax has somewhere to
           travel to without ever exposing an edge. */
        .milkyway-frame { top: -9%; bottom: -9%; }

        /* Tall enough to fill the viewport at the image's own 16:9 ratio, and
           never narrower than the viewport, because two tiles only pan
           seamlessly while one tile is at least a screen wide.
           
           Mirrored, which is not a stylistic choice. The galactic bulge sits
           at about three tenths of the way across the panorama, and the page's
           legibility scrim is heaviest across the left third — so the one part
           of this picture anybody would call "the galaxy" was landing directly
           underneath the darkest part of the page and the sky read as empty.
           Flipping puts it at seven tenths instead, well clear of the type, and
           unlike a pan offset it does that at every viewport size rather than
           at the one it was tuned for.
           
           The seam survives it, and for a reason rather than by luck. The join
           between two tiles put the image's last column next to its first, and
           that pair was measured smooth when the panorama was built. Mirroring
           each tile individually puts the same two columns next to each other
           in the opposite order, so the difference across the join is
           identical — the same measurement, unchanged. */
        .milkyway-tile { width: max(100vw, 177.78vh); transform: scaleX(-1); }

        .milkyway-pan {
          /* One tile's width in 210 seconds. Slow enough that it never pulls
             the eye off the page, fast enough that it is obviously alive if
             you rest on it for a moment.

             translateX(-50%) of a two-tile row is exactly one tile, and the
             tiles are identical, so the loop point is not merely hidden — it
             is the same pixels. */
          animation: milkyway-pan 210s linear infinite;
          will-change: transform;
        }

        @keyframes milkyway-pan {
          from { transform: translate3d(0, 0, 0); }
          to   { transform: translate3d(-50%, 0, 0); }
        }

        /* A phone is not a smaller window on the same picture. It is a much
           more zoomed-in one, and that is what made the sky read as fog rather
           than as a galaxy on a phone.

           The cause is object-cover, and it is not where you would look for
           it. Cover scales the image until it fills the box, and on a tall
           narrow screen the binding dimension is the height — so a full-height
           container blows a 16:9 panorama up until only about a fifth of its
           width fits across the screen. The galaxy's structure is all still
           there; it is just spread out past both edges, leaving the middle of
           the dust lane filling the frame. Widening the tile does nothing at
           all about this, which is worth knowing before trying it: the scale
           is set by the container's height alone.

           So on a phone the sky is a band rather than a full bleed. Fixing the
           tile at 250vw shows exactly 100/250 — two fifths — of the panorama
           across the screen, and the height follows from the image's own ratio
           so nothing is cropped in either direction. Two fifths of a panorama
           reads as a galaxy where one fifth reads as weather. The band is
           centred and its edges are masked off into the black, because space
           is black and a hard horizontal cut is not.

           The delay follows from the same numbers, and with no crop it is an
           easy sum: the fraction of the pan elapsed is exactly the image
           fraction at the left edge of the screen. The bulge sits at about 0.30
           of the width — 0.70 once the tile is mirrored, see above — so
           centring it in a 0.40-wide window means starting half way through
           the 210s cycle.

           Do not pick that number by looking for the brightest column. The
           broad blue arm further along wins on brightness per column and the
           bulge is what anyone actually means by the Milky Way; going by
           column mean opened the phone on the pale half of the picture. */
        @media (max-width: 900px) {
          .milkyway-tile { width: 250vw; }
          .milkyway-frame {
            top: calc(50% - 70.32vw);
            bottom: auto;
            height: 140.63vw;
            -webkit-mask-image: linear-gradient(to bottom, transparent 0%, #000 15%, #000 84%, transparent 100%);
            mask-image: linear-gradient(to bottom, transparent 0%, #000 15%, #000 84%, transparent 100%);
          }
          .milkyway-pan { animation-delay: -105s; }

        }

        @media (prefers-reduced-motion: reduce) {
          .milkyway-pan { animation: none; }
        }
      `}</style>
    </div>
  );
}

/**
 * The same sky behind the signed-in app: one still frame, turned right down.
 *
 * Nothing moves and nothing is measured — it is an `<img>` and two gradients.
 * A dashboard is somewhere people work, and a backdrop that drifts competes
 * with the numbers they are trying to read; this keeps the identity and drops
 * the theatre. It also never loads the 4K file, because at this opacity behind
 * a table nobody is going to find the extra detail.
 */
export function MilkyWayStill({ opacity = 0.42 }: { opacity?: number } = {}) {
  return (
    <>
      <Tile
        half
        className="absolute inset-0 h-full w-full select-none object-cover"
        style={{ opacity }}
      />
      {/* Pulls the middle of the screen — where the work is — back towards
          flat, and leaves the sky readable only at the edges. */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_42%,rgba(10,10,14,0.80)_0%,rgba(10,10,14,0.52)_50%,rgba(10,10,14,0.14)_100%)]" />
    </>
  );
}
