import type { Metadata } from "next";
import { LegalPage, Section, Bullets } from "@/components/legal-page";
import { LEGAL } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms of Service · MAIRO",
  description: "The agreement between you and MAIRO.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of service"
      intro={`The agreement between you and ${LEGAL.companyName} when you use ${LEGAL.productName}. Written to be read, not to hide things.`}
    >
      <Section heading="What MAIRO does">
        <p>
          You tell us your advertising goal and monthly budget. We build a plan, produce ad
          creative, and create and manage campaigns on the Meta ad account you connect. You watch
          the results in your dashboard and can ask our AI specialists questions.
        </p>
        <p>
          By creating an account you agree to these terms. If you don&apos;t, don&apos;t use the
          service.
        </p>
      </Section>

      <Section heading="Your account">
        <Bullets
          items={[
            "You must be 18 or older and authorised to act for the business you sign up for.",
            "Keep your password to yourself. You're responsible for what happens under your account.",
            "Give us accurate information. We build your campaigns from what you tell us, so wrong details produce wrong campaigns.",
          ]}
        />
      </Section>

      <Section heading="Your ad account and your ad spend">
        <p>This is the part worth reading twice.</p>
        <Bullets
          items={[
            "The Meta ad account stays yours. We operate it with your permission; we do not own it and cannot take it from you.",
            <><strong className="text-neutral-200">You pay Meta directly for ad spend.</strong> That is
              separate from anything you pay us. We never take custody of your ad budget.</>,
            "You set the budget. We work within it, but you are responsible for the money spent on ads.",
            "You can revoke our access at any time by disconnecting in your dashboard or in Meta's own settings.",
            "Your advertising must comply with Meta's Advertising Policies. If Meta rejects or restricts your ads, that is Meta's decision, not ours.",
          ]}
        />
      </Section>

      <Section heading="Subscription and payment">
        <p>
          Paid plans are billed monthly in advance and renew until you cancel. Cancelling stops the
          next renewal; it does not refund the current month. Prices can change, but we will tell
          you before a change affects you.
        </p>
        <p>
          Plan limits — how many campaigns and creative requests you get each month — are shown on
          the pricing page and enforced in the product.
        </p>
      </Section>

      <Section heading="Acceptable use">
        <p>You may not use {LEGAL.productName} to advertise or promote:</p>
        <Bullets
          items={[
            "Anything illegal where it runs.",
            "Anything that breaks Meta's Advertising Policies or Community Standards.",
            "Deceptive claims, fake reviews, or products you cannot deliver.",
            "Content targeting or exploiting minors.",
          ]}
        />
        <p>
          You also may not attempt to break into the service, resell access, or use it to manage ad
          accounts you are not authorised to manage. We may suspend an account that does.
        </p>
      </Section>

      <Section heading="What the AI does and doesn't guarantee">
        <p>
          Plans, ad copy, and specialist answers are generated by AI. It is genuinely useful and it
          is genuinely fallible: it can be wrong, it can misjudge your market, and it does not
          replace professional marketing, legal, or financial advice.
        </p>
        <p>
          <strong className="text-neutral-200">We do not guarantee advertising results.</strong> No
          leads, sales, reach, or return figure is promised. Advertising outcomes depend on your
          product, your market, your budget, and Meta&apos;s auction — most of which nobody
          controls. Review what we produce before it goes live.
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          We aim to keep the service running but do not promise uninterrupted access. We may change
          or discontinue features. If we discontinue the service entirely, we will give you
          reasonable notice and time to export what you need.
        </p>
      </Section>

      <Section heading="Ending it">
        <p>
          You can close your account whenever you like — see the{" "}
          <a href="/data-deletion" className="text-neutral-200 underline underline-offset-4 hover:text-white">
            data deletion page
          </a>
          . We may suspend or close an account that breaks these terms, doesn&apos;t pay, or puts
          other users at risk. Campaigns we created stay in your Meta ad account either way; they
          are yours.
        </p>
      </Section>

      <Section heading="Liability">
        <p>
          To the extent the law allows, {LEGAL.companyName} is not liable for indirect or
          consequential losses, lost profits, or lost business arising from your use of the service.
          Our total liability in any 12-month period is limited to what you paid us in that period.
        </p>
        <p>
          Nothing here excludes liability that cannot legally be excluded, and this does not affect
          consumer rights you have by law.
        </p>
      </Section>

      <Section heading="Changes">
        <p>
          We may update these terms. If a change materially affects you we will tell you by email
          before it takes effect. Continuing to use the service after that means you accept the new
          terms.
        </p>
      </Section>
    </LegalPage>
  );
}
