// Checks that .env.example and the code agree about what configuration exists.
//
//   npm run check:env
//
// A variable the code reads and this file never mentions is invisible: nobody
// setting up a deployment knows to set it, and the feature behind it is simply
// off, with no error and nothing in the UI to suggest a setting was missed.
// That is not hypothetical — STRIPE_PRICE_STUDIO and STRIPE_PRICE_AGENCY were
// read by purchasableTiers() and documented nowhere, so both freelancer plans
// silently could not be bought.
//
// The reverse rots too. A documented variable nothing reads is a setting
// somebody will dutifully fill in, and then wonder why it has no effect.
//
// Both directions have honest exceptions, and they are listed here rather than
// skipped: a name the host injects, and a name a library reads for us. Each
// exemption is itself checked, so one that stops being true fails rather than
// quietly covering something.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { priceEnvNames } from "@/lib/stripe/client";

let bad = 0;
const ok = (n: string, c: boolean, x = "") => {
  if (!c) {
    bad++;
    console.log(`  FAIL ${n} ${x}`);
  } else console.log(`  ok   ${n}`);
};

/**
 * Set by the platform, never by a person, so documenting them would be telling
 * somebody to fill in a value they must not.
 */
const HOST_PROVIDED = new Set([
  "NODE_ENV",
  // Vercel injects this into every deployment. metaRedirectUri() prefers it
  // precisely because it cannot be mistyped the way a hand-pasted URL can.
  "VERCEL_PROJECT_PRODUCTION_URL",
]);

/**
 * Read by a library rather than by this codebase, so a scan finds no call site.
 */
const READ_BY_A_LIBRARY = new Set([
  // Auth.js reads both directly off the environment.
  "AUTH_SECRET",
  "NEXTAUTH_URL",
]);

/** Files that are configuration rather than product code, and read env too. */
const EXTRA_FILES = ["prisma.config.ts"];

/** Generated by Prisma, and full of env access that is not MAIRO's. */
const SKIP_DIRS = new Set(["generated", "node_modules"]);

function sourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (SKIP_DIRS.has(entry)) continue;
      out.push(...sourceFiles(full));
    } else if (/\.(ts|tsx|mjs)$/.test(entry)) {
      out.push(full);
    }
  }
  return out;
}

/**
 * Every name the code reads off the environment directly.
 *
 * Only the literal forms, because they are the only ones a scan can be sure
 * about. Anything read through a variable — process.env[name] — is invisible
 * here by construction, which is why the dynamic families are declared below
 * rather than guessed at.
 */
/**
 * Everything that counts as a call site.
 *
 * This file is deliberately not one of them. It names variables in its own
 * exemption lists, and counting those as usage would let it excuse anything
 * simply by mentioning it — which is not hypothetical: the stale-exemption
 * check below did exactly that until it was tested.
 */
const SOURCES = [...sourceFiles("src"), ...sourceFiles("scripts"), ...EXTRA_FILES].filter(
  (file) => !file.endsWith("check-env.ts")
);

function namesReadInCode(): Map<string, string> {
  const found = new Map<string, string>();

  for (const file of SOURCES) {
    const text = readFileSync(file, "utf8");
    for (const match of text.matchAll(/process\.env\.([A-Z][A-Z0-9_]*)|process\.env\["([A-Z][A-Z0-9_]*)"\]/g)) {
      const name = match[1] ?? match[2];
      if (!found.has(name)) found.set(name, file);
    }
  }
  return found;
}

/**
 * Names read through an index expression, which no scan can see.
 *
 * Taken from the code that reads them rather than copied, so adding a tier
 * cannot add an undocumented variable.
 */
function namesReadDynamically(): string[] {
  return priceEnvNames();
}

/** Every variable .env.example declares, in the order it declares them. */
function namesDocumented(): string[] {
  const text = readFileSync(".env.example", "utf8");
  return [...text.matchAll(/^([A-Z][A-Z0-9_]*)=/gm)].map((m) => m[1]);
}

const readInCode = namesReadInCode();
const dynamic = namesReadDynamically();
const documentedList = namesDocumented();
const documented = new Set(documentedList);

console.log("\n— every variable the code reads is documented —");
{
  for (const [name, file] of [...readInCode].sort()) {
    if (HOST_PROVIDED.has(name)) continue;
    ok(`${name} is in .env.example`, documented.has(name), `read in ${file}`);
  }
}

console.log("\n— including the ones no scan can see —");
{
  // The bug this check was written for. These are read as process.env[x], so
  // the scan above finds nothing and a missing one looks like a variable that
  // simply does not exist.
  for (const name of dynamic.sort()) {
    ok(`${name} is in .env.example`, documented.has(name), "read via PRICE_ENV");
  }
}

console.log("\n— and every documented variable is read by something —");
{
  const dynamicSet = new Set(dynamic);
  for (const name of documentedList) {
    if (READ_BY_A_LIBRARY.has(name) || dynamicSet.has(name)) continue;
    ok(`${name} is used`, readInCode.has(name), "documented but nothing reads it");
  }
}

console.log("\n— nothing is declared twice —");
{
  // Two declarations of one variable means whichever comes last wins, silently,
  // and the one somebody edited may not be it.
  const counts = new Map<string, number>();
  for (const name of documentedList) counts.set(name, (counts.get(name) ?? 0) + 1);
  const duplicates = [...counts].filter(([, n]) => n > 1).map(([name]) => name);
  ok("no variable is declared twice in .env.example", duplicates.length === 0, duplicates.join(", "));
}

console.log("\n— the exemptions above are still true —");
{
  // An allowlist nobody revisits is how a check stops checking. If a name here
  // has no call site left at all, the exemption is covering nothing and should
  // go — and if it is still read, the entry has to stay.
  const everywhere = SOURCES.map((f) => readFileSync(f, "utf8")).join("\n");

  for (const name of HOST_PROVIDED) {
    ok(`${name} is still read somewhere`, everywhere.includes(name), "stale exemption");
  }
  for (const name of READ_BY_A_LIBRARY) {
    ok(`${name} is still documented`, documented.has(name), "stale exemption");
  }
}

console.log(bad === 0 ? "\nAll checks passed.\n" : `\n${bad} FAILED\n`);
process.exit(bad === 0 ? 0 : 1);
