import Link from "next/link";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { after } from "next/server";
import { touchActivity } from "@/lib/success/store";
import { FeedbackButton } from "@/components/success/feedback";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { signOutAction } from "@/lib/actions/auth-actions";
import { AppShell } from "@/components/mairo/app-shell";
import { MairoAssistant } from "@/components/mairo/assistant";
import { findOrCreateThread, loadThreadMessages } from "@/lib/ai/threads";
import { assistantNameOf, CLIENT_AGENT } from "@/lib/ai/agents";
import { recentNotifications, unreadCount } from "@/lib/notifications/notify";
import { toBellItem } from "@/lib/notifications/present";
import { NotificationBell } from "@/components/mairo/notification-bell";
import { hasActivePlan } from "@/lib/readiness";
import { viewMode } from "@/lib/view-mode";
import { Tour } from "@/components/tour";
import { hasSeenTour } from "@/lib/actions/tour-actions";
import { OWNER_TOUR } from "./tour-steps";
import { isExploring } from "@/lib/explore-mode";
import { activeOrg } from "@/lib/active-org";
import { FREE_NAV, SOCIAL_LOCKED_NAV, SOCIAL_NAV } from "./free-nav";
import { socialAccess } from "@/lib/social/access";
import { LOCKED_NAV, LockedArea, isFreePage } from "@/components/strategy/free-access";

// Pages the not-yet-connected client can still open.
//
// /dashboard/meta is the obvious one — it is where the funnel sends them and
// there has to be somewhere to land. Settings is the less obvious one, and
// leaving it out was a trap: someone who mistyped their business name at
// signup is by definition someone who has not connected an ad account yet, so
// gating the only screen that fixes it behind connecting one leaves them stuck
// with a name the AI will put in every ad it writes.
//
// /dashboard/integrations joins them for the same reason as /dashboard/meta:
// it is now the screen that lists every network a business can connect, and
// gating "connect somewhere to advertise" behind having connected somewhere
// to advertise is the same trap in a wider form.
// /dashboard/leads is here on the same principle rather than as a convenience.
// The lead form is a page MAIRO hosts at /f/<slug>; it does not live on Meta,
// does not need an ad account to exist, and works the moment it is written.
// Onboarding now sends anyone who answered "they fill in a form" straight to it,
// and gating the one thing that does not depend on Meta behind connecting Meta
// would send them to a screen they were not ready for and lose the answer they
// had just given.
const ALWAYS_REACHABLE = [
  // The first-campaign checklist, which is where connecting Meta starts for
  // a business that came through the free plan.
  "/dashboard/launch",
  "/dashboard/meta",
  "/dashboard/integrations",
  "/dashboard/settings",
  "/dashboard/guide",
  "/dashboard/leads",
];

export default async function DashboardLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();
  if (!session?.user?.organizationId) redirect("/sign-in");
  const active = await activeOrg();
  const organizationId = active?.id ?? session.user.organizationId;

  // A freelancer who has not opened a client yet has nothing to show here —
  // their workspace runs no ads of its own. Send them to pick one.
  if (session.user.role === "FREELANCER" && !active?.actingAsClient) {
    redirect("/clients");
  }

  const pathname = (await headers()).get("x-pathname") ?? "";

  // Everything the shell needs, read in one round rather than one after
  // another — each await in a row is another wait on the database before the
  // screen can show anything.
  const [organization, intake, metaAccount, seenTour, socialPosting, exploring, journeyRow, mode, bellRows, unread] = await Promise.all([
    db.organization.findUnique({
      where: { id: organizationId },
      select: {
        name: true,
        subscriptionTier: true,
        subscriptionStatus: true, paymentRequired: true,
        assistantName: true,
      },
    }),
    db.onboardingIntake.findUnique({ where: { organizationId }, select: { id: true } }),
    db.metaAdAccount.findUnique({ where: { organizationId }, select: { id: true } }),
    hasSeenTour(),
    socialAccess(organizationId).then((a) => a.ok),
    isExploring(),
    active?.actingAsClient
      ? null
      : db.strategyPlan.findUnique({ where: { organizationId }, select: { status: true, activatedAt: true } }),
    viewMode(),
    // The bell's contents, rendered server-side. These are generated by a
    // daily sweep, so that is exactly as fresh as the data is — polling would
    // cost a request a minute to say the same thing.
    recentNotifications(organizationId, 6),
    unreadCount(organizationId),
  ]);


  // Enforce the intended funnel: sign up -> onboarding -> connect Meta ->
  // rest of the dashboard. /dashboard/meta itself is exempt from the second
  // check so there's somewhere for a not-yet-connected client to land.
  //
  // "Explore first" is the one way past the Meta step, and it is deliberate:
  // the visitor has to click it, every page then carries a banner saying the
  // account is not connected, and nothing that would actually spend money
  // works until it is. Without it, anyone Meta hasn't approved as a tester
  // cannot see past this screen at all.
  if (!intake) redirect("/onboarding");

  // FREE shows what MAIRO would do; PAID is MAIRO doing it. A business that
  // signed up through the free plan and hasn't subscribed gets its plan, its
  // business, connected accounts and pricing; every page that runs real
  // advertising shows a locked preview instead. The server refuses those
  // actions too (billing/execution) — this is the screen, not the lock.
  const journey = journeyRow;
  const paid = organization ? hasActivePlan(organization) : false;
  const unpaid = Boolean(organization?.paymentRequired) && !paid && !active?.actingAsClient;
  const approved = journey?.status === "APPROVED";
  let lockedHere = false;
  if (unpaid) {
    if (pathname.startsWith("/dashboard/launch")) redirect(approved ? "/plan/activate" : "/plan");
    lockedHere = !isFreePage(pathname);
  } else if (journey && !journey.activatedAt) {
    // Paid, not yet turned into a campaign: the plan must be approved, then
    // the launch checklist takes over.
    if (!approved) redirect("/plan");
    if (!["/dashboard/launch", "/dashboard/billing"].some((p) => pathname.startsWith(p))) redirect("/dashboard/launch");
  }

  if (!unpaid && !metaAccount && !exploring && !ALWAYS_REACHABLE.some((p) => pathname.startsWith(p))) {
    redirect(journey ? "/dashboard/launch" : "/dashboard/meta?required=1");
  }

  // When the business last opened MAIRO, for the team's customer-success
  // view. After the page is sent, and at most one write an hour.
  after(() => touchActivity(organizationId).catch(() => undefined));

  // The assistant's thread. Same thread the full-page chat uses, so the panel
  // and the page are one conversation rather than two that each forget the
  // other. Created lazily on first dashboard load and reused after that.
  const assistant =
    organization && hasActivePlan(organization) && session.user.id
      ? await (async () => {
          const thread = await findOrCreateThread(session.user.id!, organizationId, CLIENT_AGENT);
          return { threadId: thread.id, messages: await loadThreadMessages(thread.id) };
        })()
      : null;

  return (
    <AppShell
      mode={mode}
      businessName={organization?.name ?? ""}
      userName={session.user.name ?? ""}
      showUpgrade={organization?.subscriptionTier !== "AGENCY"}
      assistantName={assistantNameOf(organization?.assistantName)}
      // Social Manager is Scale-only: active Scale gets its section; every
      // other plan sees it locked, labelled Scale, leading to the upgrade.
      // A short sidebar: Social Manager (Scale) or its locked entry; the free
      // plan's two pages before subscribing. Enquiries lives inside Campaigns.
      extraNav={[...(socialPosting && !unpaid ? SOCIAL_NAV : [SOCIAL_LOCKED_NAV]), ...(unpaid ? FREE_NAV(approved) : [])]}
      scale={socialPosting && !unpaid}
      locked={[...(unpaid ? LOCKED_NAV : []), ...(socialPosting && !unpaid ? [] : ["/dashboard/social"])]}
      notifications={
        <NotificationBell items={bellRows.map((n) => toBellItem(n))} unread={unread} />
      }
      footer={
        <>
        <FeedbackButton />
        <form action={signOutAction}>
          <button
            type="submit"
            className="w-full rounded-xl px-3 py-[7px] text-left text-[13px] text-faint transition-colors hover:bg-white/[0.04] hover:text-white"
          >
            Sign out
          </button>
        </form>
        </>
      }
    >
      {/* Offered on the first visit after setup, and on demand after that.
          Mounted in the layout so it works from whichever screen someone
          starts it on — every step points at the sidebar, which is always
          there.

          Gated on having finished onboarding rather than on a query
          parameter, because a layout cannot read one, and because being
          shown around before you have told MAIRO what your business is would
          be a tour of screens that have nothing in them yet.

          Whether they have seen it comes from their user row, not from the
          browser — so signing in on a phone, in a private window, or after
          clearing site data does not start it again. */}
      {/* Starts on the dashboard home, not on whatever screen happens to be
          first. Onboarding now drops anyone who answered "they fill in a form"
          onto /dashboard/leads to write it, and the tour was opening on top of
          that — a nine-step walkthrough of the product over the one task they
          were sent there to finish. A tour of the dashboard belongs on the
          dashboard; it is still available on demand from Account. */}
      <Tour
        steps={OWNER_TOUR}
        autoStart={Boolean(intake) && pathname === "/dashboard" && !unpaid}
        alreadySeen={seenTour}
      />

      {/* Whose account you are in, and the way back out. A freelancer moving
          between clients needs this on every screen — editing the wrong
          business's campaigns because you forgot which one you had open is
          exactly the mistake this prevents. */}
      {active?.actingAsClient && (
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3">
          <p className="text-sm text-neutral-300">
            Working in <span className="font-medium text-white">{organization?.name}</span>
          </p>
          <Link
            href="/clients"
            className="shrink-0 rounded-lg border border-white/15 px-4 py-2 text-xs text-neutral-300 transition hover:border-white/40 hover:text-white"
          >
            All clients
          </Link>
        </div>
      )}

      {!metaAccount && !unpaid && !pathname.startsWith("/dashboard/launch") && (
        <div className="mb-6 flex flex-col gap-3 rounded-2xl border border-amber-500/30 bg-amber-500/[0.06] p-4 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm text-amber-200">
            You&apos;re looking around without a Meta account connected. Plans and
            creatives work, but nothing can go live until you connect one.
          </p>
          <Link
            href="/dashboard/meta"
            className="shrink-0 rounded-lg border border-amber-400/40 px-4 py-2 text-xs uppercase tracking-[0.1em] text-amber-100 transition hover:bg-amber-400 hover:text-black"
          >
            Connect Meta
          </Link>
        </div>
      )}
      {lockedHere ? <LockedArea pathname={pathname} approved={approved} /> : children}

      {/* MAIRO, reachable from every screen. Mounted here rather than per page
          for the same reason the tour is: it has to be available wherever
          somebody gets stuck, and the thread is the account's, not the page's.

          Only for accounts whose plan includes it — the endpoint costs real
          money to serve and already refuses without one, so a launcher that
          opens onto a refusal would be a button that lies. */}
      {assistant && (
        <MairoAssistant
          threadId={assistant.threadId}
          initialMessages={assistant.messages}
          businessName={organization?.name ?? "your business"}
          assistantName={assistantNameOf(organization?.assistantName)}
        />
      )}
    </AppShell>
  );
}
